services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: llm-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: llm_stock
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
