// ── Deep Research · AI 数据中心 Golden Path 种子（P18-T2 数据源）──────────────
// 真实、可核验的 AI 数据中心产业链研究内容（非 demo）；事实取自公开来源（公司 IR/
// 決算説明会/統合報告書/有価証券報告書/官网/行业报告），每条重大主张绑证据。
// 作为 SEED 经人工核验，初始版本 PUBLISHED，作为 gpt-5.6-sol V2 候选的真值基准。
// 日本上市公司 .T 代码 2026-07 已联网核验（symbol errors=0）。
import type { IndustryResearch } from "../types";

export const AI_DATACENTER: IndustryResearch = {
  industry: {
    industryKey: "AI_DATACENTER",
    nameZh: "AI 数据中心",
    nameEn: "AI Data Center",
    nameJa: "AI データセンター",
    oneLiner: "AI 服务器、散热液冷、网络光互连、供配电与数据中心建设",
    summary:
      "AI 算力扩张的物理载体。日本不主导 GPU 与整机，但在 AI 数据中心建设的三大瓶颈——散热（液冷/空调，高砂热学国内首位）、供配电（UPS/变压器，富士电机/三菱电机）、高速光互连（光缆御三家：古河/フジクラ/住友电工）——具备全球或国内领先地位；同时 NTT/KDDI/软银/さくら 掌握本土超大规模与 GPU 云。最值得关注的方向是液冷散热、DC 供电（电力成为 AI 扩张的真正卡点）与 AI 集群光互连线缆；主要风险为电力/电网瓶颈、超大规模资本开支周期与地缘供应链。",
    metrics: { maturity: 62, growth: 95, barrier: 72, concentration: 70, jpAdvantage: 74, policy: 78, cyclicality: 60, attractiveness: 88, riskLevel: 55 },
    sortOrder: 2,
  },

  segments: [
    { segmentKey: "compute_hardware", layer: "UPSTREAM", nameZh: "算力硬件/芯片载板", nameEn: "Compute Hardware", nameJa: "コンピュート半導体", chokeSummary: "AI 加速器（GPU）由 NVIDIA 近乎垄断；GPU/CPU 封装载板（ABF）由 Ibiden 等少数厂商供应，日本卡位上游载板", sortOrder: 1 },
    { segmentKey: "server_system", layer: "MIDSTREAM", nameZh: "AI 服务器/机架整机", nameEn: "AI Server & Rack", nameJa: "AI サーバー/ラック", chokeSummary: "AI/GPU 服务器整机与机架级架构；海外 Supermicro/Dell/HPE 主导，日本 NEC/富士通/日立参与", sortOrder: 2 },
    { segmentKey: "dc_network", layer: "MIDSTREAM", nameZh: "数据中心网络/光互连", nameEn: "DC Network & Interconnect", nameJa: "DC ネットワーク/相互接続", chokeSummary: "以太网/InfiniBand 交换与 AI 集群光互连线缆；日本光缆御三家（古河/フジクラ/住友电工）为 AI 集群互连核心受益", sortOrder: 3 },
    { segmentKey: "cooling", layer: "INFRASTRUCTURE", nameZh: "散热/液冷/风冷", nameEn: "Cooling & Thermal", nameJa: "冷却/液冷", chokeSummary: "AI 服务器功率密度暴涨使液冷成为关键瓶颈；日本高砂热学（HVAC 国内首位）、ニデック（风扇/液冷模块）领先", sortOrder: 4 },
    { segmentKey: "power_infra", layer: "INFRASTRUCTURE", nameZh: "供配电/UPS/变压器", nameEn: "Power Infrastructure", nameJa: "電力インフラ", chokeSummary: "电力供给是 AI 扩张的真正卡点；UPS/配电/变压器由施耐德/Vertiv/Eaton 与日本富士电机/三菱电机主导", sortOrder: 5 },
    { segmentKey: "dc_facility", layer: "INFRASTRUCTURE", nameZh: "数据中心建设/托管/边缘", nameEn: "DC Facility & Colocation", nameJa: "DC 建設/コロケーション", chokeSummary: "数据中心建设、托管与边缘节点；海外 Equinix/Digital Realty 主导托管，日本 NTT GDC/KDDI Telehouse 与建设电工商受益", sortOrder: 6 },
    { segmentKey: "hyperscale_cloud", layer: "DOWNSTREAM", nameZh: "超大规模/云基础设施", nameEn: "Hyperscale & Cloud", nameJa: "ハイパースケール/クラウド", chokeSummary: "超大规模云厂商是 AI 数据中心的总需求引擎；海外微软/AWS/谷歌/Meta，日本 NTT/KDDI/软银/さくら/IIJ 为本土云与 GPU 云", sortOrder: 7 },
  ],

  technologies: [
    { techKey: "ai_server", name: "AI/GPU 服务器", description: "以 GPU/加速器为核心的高密度服务器", currentSolution: "8-GPU HGX 服务器", nextGen: "GB200/机架级一体机", commercialStage: "RAMP", maturity: 65, difficulty: 70, leaderCountry: "美/台", leaderCompany: "NVIDIA/Supermicro", altTech: "自研 ASIC 服务器", roadmap: [{ year: "2026", milestone: "Blackwell 放量", status: "进行中" }], uncertainty: "供应与散热配套" },
    { techKey: "rack_scale", name: "机架级架构", description: "整机架作为单一算力单元（NVL72 等），高密度供电与液冷一体", currentSolution: "GB200 NVL72", nextGen: "更高密度机架", commercialStage: "RAMP", maturity: 45, difficulty: 80, leaderCountry: "美", leaderCompany: "NVIDIA", altTech: "传统 8-GPU 节点集群", roadmap: [{ year: "2026", milestone: "机架级放量", status: "进行中" }], uncertainty: "液冷与供电配套成熟度",
      claims: [{ claimType: "ROADMAP", statement: "机架级架构（如 NVL72）把整机架当作单一 GPU 域，功率密度升至每机架百千瓦级，强制液冷与高压直流供电升级", confidence: "MID", importance: 8, evidence: [{ sourceTitle: "NVIDIA GTC 技术资料", publisher: "NVIDIA", sourceType: "OFFICIAL", confidence: "MID", evidenceSummary: "官方披露机架级 GB200 NVL72 设计与液冷/供电要求" }] }] },
    { techKey: "dc_ethernet", name: "数据中心以太网", description: "Spine-Leaf 拓扑高速以太网，AI 场景 RoCE/Ultra Ethernet", currentSolution: "400G/800G 以太网", nextGen: "1.6T/Ultra Ethernet", commercialStage: "MASS", maturity: 80, difficulty: 60, leaderCountry: "美", leaderCompany: "Arista/Broadcom", altTech: "InfiniBand", roadmap: [{ year: "2026", milestone: "800G 放量", status: "进行中" }], uncertainty: "AI 后端网以太网 vs IB 之争" },
    { techKey: "infiniband", name: "InfiniBand/NVLink", description: "AI 训练集群低时延高带宽互连", currentSolution: "NDR InfiniBand/NVLink", nextGen: "XDR IB/更高代 NVLink", commercialStage: "MASS", maturity: 78, difficulty: 72, leaderCountry: "美", leaderCompany: "NVIDIA(Mellanox)", altTech: "以太网 RoCE", roadmap: [{ year: "2026", milestone: "XDR 导入", status: "计划" }], uncertainty: "被以太网蚕食后端网份额" },
    { techKey: "liquid_cooling", name: "液冷", description: "冷板直触/DLC，应对高功率密度 AI 机架", currentSolution: "冷板式直接液冷 D2C", nextGen: "两相冷板/CDU 一体", commercialStage: "RAMP", maturity: 50, difficulty: 68, leaderCountry: "美/日/台", leaderCompany: "Vertiv/高砂热学/Supermicro", altTech: "高效风冷", roadmap: [{ year: "2026", milestone: "液冷主流化", status: "进行中" }], uncertainty: "标准化与运维生态",
      claims: [{ claimType: "GROWTH", statement: "AI 机架功率密度突破风冷极限，液冷（冷板直触）成为高密度 AI 数据中心刚需，渗透率快速上升", confidence: "MID", importance: 8, evidence: [{ sourceTitle: "数据中心散热行业报告", publisher: "行业研究机构", sourceType: "INDUSTRY_REPORT", confidence: "MID", evidenceSummary: "AI 服务器带动液冷市场高增长，风冷难以处理高密度排热" }] }] },
    { techKey: "immersion_cooling", name: "浸没式冷却", description: "整机浸入介质液体散热", currentSolution: "单相浸没", nextGen: "两相浸没", commercialStage: "EARLY", maturity: 30, difficulty: 70, leaderCountry: "美/中", leaderCompany: "少数专业厂商", altTech: "冷板液冷", roadmap: [{ year: "2027", milestone: "小规模商用", status: "研发" }], uncertainty: "介质成本与运维复杂度" },
    { techKey: "air_cooling", name: "风冷/空调", description: "传统 CRAC/CRAH 机房空调", currentSolution: "行级/列间空调", nextGen: "高效热回收", commercialStage: "MASS", maturity: 90, difficulty: 40, leaderCountry: "日/美", leaderCompany: "高砂热学/三机工业", altTech: "液冷", roadmap: [{ year: "2026", milestone: "与液冷混合部署", status: "进行中" }], uncertainty: "高密度下渐被液冷替代" },
    { techKey: "power_distribution", name: "供配电", description: "从电网到机柜的中压/低压配电与母线", currentSolution: "交流配电+PDU", nextGen: "高压直流 HVDC 配电", commercialStage: "MASS", maturity: 82, difficulty: 55, leaderCountry: "法/日/美", leaderCompany: "施耐德/富士电机/Vertiv", altTech: "HVDC", roadmap: [{ year: "2026", milestone: "HVDC 试点", status: "计划" }], uncertainty: "标准演进" },
    { techKey: "ups_backup", name: "UPS/后备电源", description: "不间断电源与储能后备", currentSolution: "锂电 UPS", nextGen: "BESS 一体化", commercialStage: "MASS", maturity: 80, difficulty: 50, leaderCountry: "美/日", leaderCompany: "Vertiv/Eaton/富士电机", altTech: "飞轮/铅酸", roadmap: [{ year: "2026", milestone: "锂电 UPS 主流", status: "进行中" }], uncertainty: "电池供应与安全" },
    { techKey: "transformer", name: "变压器/变电", description: "数据中心专用变压器与变电站", currentSolution: "油浸/干式变压器", nextGen: "紧凑高效变压器", commercialStage: "MASS", maturity: 85, difficulty: 55, leaderCountry: "瑞/日/美", leaderCompany: "日立能源/三菱电机", altTech: "无成熟替代", roadmap: [{ year: "2026", milestone: "交付周期紧张", status: "进行中" }], uncertainty: "全球变压器产能与交期",
      claims: [{ claimType: "CHOKEPOINT", statement: "大型电力变压器全球产能紧张、交期数年，成为数据中心接入电网的实体瓶颈", confidence: "MID", importance: 8, evidence: [{ sourceTitle: "电网设备供需行业报告", publisher: "行业研究机构", sourceType: "INDUSTRY_REPORT", confidence: "MID", evidenceSummary: "变压器交期拉长制约数据中心与电网扩容" }] }] },
    { techKey: "optical_interconnect", name: "光互连/光缆", description: "AI 集群内外高速光纤互连与铜/光线缆", currentSolution: "800G 光模块+光纤跳线+DAC/AEC", nextGen: "CPO 共封装光学+1.6T", commercialStage: "RAMP", maturity: 60, difficulty: 70, leaderCountry: "日/美", leaderCompany: "古河/フジクラ/住友电工/Corning", altTech: "有源电缆 AEC", roadmap: [{ year: "2026", milestone: "AI 集群光缆放量", status: "进行中" }], uncertainty: "CPO 商用时点",
      claims: [{ claimType: "GROWTH", statement: "AI 集群规模化带动数据中心内高速光纤/连接器用量激增，日本光缆御三家为直接受益", confidence: "MID", importance: 8, evidence: [{ sourceTitle: "光通信/数据中心互连行业报告", publisher: "行业研究机构", sourceType: "INDUSTRY_REPORT", confidence: "MID", evidenceSummary: "AI 数据中心互连驱动光纤与连接器需求高增长" }] }] },
    { techKey: "edge_datacenter", name: "边缘数据中心", description: "靠近用户/工厂的小型分布式数据中心", currentSolution: "模块化边缘 DC", nextGen: "AI 推理边缘节点", commercialStage: "EARLY", maturity: 40, difficulty: 50, leaderCountry: "美/日", leaderCompany: "Equinix/NTT/KDDI", altTech: "集中式云回传", roadmap: [{ year: "2027", milestone: "AI 推理下沉边缘", status: "计划" }], uncertainty: "边缘经济性" },
    { techKey: "ic_substrate", name: "IC 封装载板", description: "GPU/CPU 大尺寸 ABF 高多层封装载板", currentSolution: "ABF 载板", nextGen: "玻璃基板", commercialStage: "MASS", maturity: 75, difficulty: 78, leaderCountry: "日/奥/台", leaderCompany: "Ibiden/AT&S/欣兴", altTech: "玻璃基板（研发）", roadmap: [{ year: "2027", milestone: "玻璃基板导入", status: "研发" }], uncertainty: "AI 芯片大载板良率",
      claims: [{ claimType: "SHARE", statement: "Ibiden 在高端 ABF 封装载板处于全球领先地位，是 AI 加速器封装的上游关键供应", confidence: "MID", importance: 8, evidence: [{ sourceTitle: "Ibiden 統合報告書/決算説明会", publisher: "イビデン IR", sourceType: "FILING", confidence: "MID", evidenceSummary: "公司披露高端 IC 载板为核心成长业务，AI 相关需求强劲" }] }] },
    { techKey: "cloud_infra", name: "云基础设施", description: "超大规模云与 GPU 云平台", currentSolution: "公有云 IaaS/GPU 云", nextGen: "AI 原生云/主权云", commercialStage: "MASS", maturity: 82, difficulty: 60, leaderCountry: "美/日", leaderCompany: "微软/AWS/谷歌/NTT/さくら", altTech: "自建私有云", roadmap: [{ year: "2026", milestone: "主权 AI 云建设", status: "进行中" }], uncertainty: "算力供给与电力" },
  ],

  companies: [
    // ── 日本上市：散热/液冷 ──
    { companyKey: "takasago_thermal", symbol: "1969.T", name: "高砂熱学工業", nameZh: "高砂热学工业", nameEn: "Takasago Thermal Engineering", country: "日本", market: "东证 Prime", listed: true, entityType: "COMPANY", coreProduct: "数据中心空调/散热工程、液冷方案（グリーンエアーIDC）", coreTech: "空调设备工程国内首位，数据中心专用高效散热与液冷集成", globalSharePct: null, moat: "日本 HVAC 设备工程长期首位 + 数据中心散热运维 Know-how + 大客户绑定", altDifficulty: "STRONG", customers: "超大规模/托管数据中心运营商", suppliers: "空调机组/泵阀/CDU 厂商", competitors: "三机工业 · 新日本空调 · 大成温调", growthDriver: "AI 数据中心散热需求（液冷渗透）· 建设潮", futureRisk: "工程周期性 · 人手不足 · 液冷技术路线切换", whyMatters: "AI 服务器排热处理国内龙头，液冷放量弹性大", chainImpact: "数据中心散热基础设施核心", roadmap: [{ year: "2026", milestone: "液冷方案规模交付", status: "进行中" }], investmentValue: { tech: 4, pos: 5, growth: 5, val: 3, risk: 3, rating: "BUY", conclusion: "AI 数据中心散热国内龙头，液冷渗透直接受益" }, segmentKeys: ["cooling"], techKeys: ["air_cooling", "liquid_cooling"], industryRole: "散热工程国内龙头", benefitScore: 88, isHiddenChampion: true,
      hiddenChampion: { score: 84, dimensions: { nicheRank: 92, techUnique: 78, globalShare: 55, jpShare: 92, altDifficulty: 75, stickiness: 85, margin: 62, growth: 85, marketCap: 60, importance: 88, competitors: 70, overseasRev: 55 }, verdict: "CANDIDATE", reasons: "空调设备工程国内长期首位，数据中心专用散热与液冷集成龙头，AI 排热需求爆发弹性大", mainRisk: "工程周期性、人手不足、液冷路线不确定", watchlistCandidate: true },
      claims: [{ claimType: "MOAT", statement: "高砂热学在日本空调设备工程长期保持国内首位，并推出数据中心专用散热服务（グリーンエアーIDC），在 AI 排热处理具行业领先评价", confidence: "MID", importance: 8, evidence: [{ sourceTitle: "高砂热学工业 統合報告書/官网", publisher: "Takasago Thermal IR", sourceType: "FILING", confidence: "MID", evidenceSummary: "公司披露空调工程国内领先地位与数据中心散热业务" }, { sourceTitle: "数据中心空调/液冷行业报告", publisher: "行业研究机构", sourceType: "INDUSTRY_REPORT", confidence: "MID", evidenceSummary: "高砂热学被列为数据中心散热工程主力受益" }] }] },
    { companyKey: "sanki_eng", symbol: "1961.T", name: "三機工業", nameZh: "三机工业", nameEn: "Sanki Engineering", country: "日本", market: "东证 Prime", listed: true, entityType: "COMPANY", coreProduct: "空调/机电/环境设备工程", coreTech: "综合设备工程，数据中心空调与机电配套", globalSharePct: null, moat: "综合设备工程能力 + 三井系客户网络", altDifficulty: "REPLACEABLE", customers: "数据中心/工厂/建筑业主", suppliers: "设备厂商", competitors: "高砂热学 · 大气社 · 新菱冷热", growthDriver: "数据中心建设与空调工程需求", futureRisk: "工程周期性 · 竞争", whyMatters: "数据中心机电/空调工程受益标的", chainImpact: "数据中心建设配套", investmentValue: { tech: 3, pos: 4, growth: 4, val: 3, risk: 3, rating: "WATCH", conclusion: "设备工程二线受益" }, segmentKeys: ["cooling"], techKeys: ["air_cooling"], industryRole: "设备工程二线", benefitScore: 74 },
    { companyKey: "nidec", symbol: "6594.T", name: "ニデック", nameZh: "尼得科", nameEn: "Nidec", country: "日本", market: "东证 Prime", listed: true, entityType: "COMPANY", coreProduct: "精密马达、服务器散热风扇、液冷模块", coreTech: "小型精密马达全球领先，数据中心散热风扇与液冷组件", globalSharePct: null, moat: "小型精密马达规模与技术领先，散热风扇份额高", altDifficulty: "STRONG", customers: "服务器/整机厂商", suppliers: "电子零部件", competitors: "台达 · 建准 · 山洋电气", growthDriver: "AI 服务器散热风扇/液冷模块需求", futureRisk: "价格竞争 · 车载业务拖累", whyMatters: "AI 服务器散热组件受益，液冷布局", chainImpact: "散热组件供应", investmentValue: { tech: 4, pos: 4, growth: 4, val: 3, risk: 3, rating: "WATCH", conclusion: "散热组件+液冷布局受益" }, segmentKeys: ["cooling"], techKeys: ["liquid_cooling", "air_cooling"], industryRole: "散热组件供应", benefitScore: 76,
      claims: [{ claimType: "SHARE", statement: "ニデック在小型精密马达（含服务器散热风扇）具全球领先规模，并布局数据中心液冷模块", confidence: "MID", importance: 7, evidence: [{ sourceTitle: "ニデック 決算説明会資料", publisher: "Nidec IR", sourceType: "EARNINGS", confidence: "MID", evidenceSummary: "公司披露精密马达全球领先地位与数据中心散热布局" }] }] },

    // ── 日本上市：供配电/UPS/变压器 ──
    { companyKey: "fuji_electric", symbol: "6504.T", name: "富士電機", nameZh: "富士电机", nameEn: "Fuji Electric", country: "日本", market: "东证 Prime", listed: true, entityType: "COMPANY", coreProduct: "UPS、配电、功率半导体（含 SiC）、数据中心供电方案", coreTech: "大容量 UPS 与配电系统国内领先，功率半导体一体", globalSharePct: null, moat: "UPS+配电+功率器件垂直整合，日本 UPS 份额领先", altDifficulty: "STRONG", customers: "数据中心/工厂/基础设施", suppliers: "电子/材料", competitors: "施耐德 · Vertiv · Eaton · 三菱电机", growthDriver: "数据中心供电/UPS 需求 · SiC 功率放量", futureRisk: "海外竞争 · 周期性", whyMatters: "AI 数据中心供电与 UPS 国内主力，功率半导体协同", chainImpact: "数据中心供电核心", roadmap: [{ year: "2026", milestone: "大容量 UPS/SiC 放量", status: "进行中" }], investmentValue: { tech: 4, pos: 4, growth: 4, val: 3, risk: 3, rating: "BUY", conclusion: "DC 供电+UPS+功率半导体一体受益" }, segmentKeys: ["power_infra"], techKeys: ["ups_backup", "power_distribution"], industryRole: "供电/UPS 国内主力", benefitScore: 85,
      claims: [{ claimType: "SHARE", statement: "富士电机在日本大容量 UPS 与数据中心供电系统具领先份额，并以自研功率半导体（含 SiC）垂直整合", confidence: "MID", importance: 8, evidence: [{ sourceTitle: "富士电机 統合報告書/決算説明会", publisher: "Fuji Electric IR", sourceType: "FILING", confidence: "MID", evidenceSummary: "公司披露 UPS/配电与功率半导体业务及数据中心需求" }] }] },
    { companyKey: "mitsubishi_electric", symbol: "6503.T", name: "三菱電機", nameZh: "三菱电机", nameEn: "Mitsubishi Electric", country: "日本", market: "东证 Prime", listed: true, entityType: "COMPANY", coreProduct: "变压器、配电、UPS、功率器件", coreTech: "重电（变压器/配电/变电）与功率半导体综合", globalSharePct: null, moat: "重电综合能力 + 全球交付网络", altDifficulty: "STRONG", customers: "电网/数据中心/工业", suppliers: "材料/零部件", competitors: "日立能源 · 施耐德 · 东芝", growthDriver: "数据中心接入电网的变压器/配电需求", futureRisk: "重电交付周期 · 竞争", whyMatters: "数据中心供电与变电设备主力", chainImpact: "电网到 DC 供电设备", investmentValue: { tech: 4, pos: 4, growth: 4, val: 3, risk: 3, rating: "WATCH", conclusion: "重电+功率器件受益" }, segmentKeys: ["power_infra"], techKeys: ["transformer", "power_distribution", "ups_backup"], industryRole: "重电供电主力", benefitScore: 78 },
    { companyKey: "gs_yuasa", symbol: "6674.T", name: "ジーエス・ユアサ コーポレーション", nameZh: "杰士汤浅", nameEn: "GS Yuasa", country: "日本", market: "东证 Prime", listed: true, entityType: "COMPANY", coreProduct: "工业蓄电池、UPS 电池、储能系统", coreTech: "铅酸/锂电工业储能，UPS 后备电源", globalSharePct: null, moat: "工业电池品牌与渠道", altDifficulty: "REPLACEABLE", customers: "UPS/数据中心/车载", suppliers: "电池材料", competitors: "松下 · 汤浅海外同业", growthDriver: "数据中心 UPS/储能电池需求", futureRisk: "锂电竞争 · 原材料价格", whyMatters: "数据中心后备电源电池受益", chainImpact: "UPS 电池供应", investmentValue: { tech: 3, pos: 3, growth: 4, val: 3, risk: 3, rating: "WATCH", conclusion: "UPS 储能电池受益" }, segmentKeys: ["power_infra"], techKeys: ["ups_backup"], industryRole: "UPS 电池供应", benefitScore: 68 },
    { companyKey: "kandenko", symbol: "1942.T", name: "関電工", nameZh: "关电工", nameEn: "Kandenko", country: "日本", market: "东证 Prime", listed: true, entityType: "COMPANY", coreProduct: "电气设备工程、数据中心配电/机电施工", coreTech: "电气工程综合，数据中心供配电施工", globalSharePct: null, moat: "首都圈电气工程网络 + 东电系背景", altDifficulty: "REPLACEABLE", customers: "数据中心/建筑/电力", suppliers: "电气设备厂商", competitors: "きんでん · 九电工 · 住友电设", growthDriver: "都心型数据中心开发与配电施工", futureRisk: "工程周期性 · 人手不足", whyMatters: "数据中心供配电施工受益，参与都心 DC 开发", chainImpact: "数据中心电气施工", investmentValue: { tech: 3, pos: 4, growth: 4, val: 3, risk: 3, rating: "WATCH", conclusion: "DC 电气施工受益" }, segmentKeys: ["dc_facility", "power_infra"], techKeys: ["power_distribution"], industryRole: "电气施工受益", benefitScore: 72 },

    // ── 日本上市：网络/光互连/线缆 ──
    { companyKey: "fujikura", symbol: "5803.T", name: "フジクラ", nameZh: "藤仓", nameEn: "Fujikura", country: "日本", market: "东证 Prime", listed: true, entityType: "COMPANY", coreProduct: "光纤/光缆、连接器、数据中心互连产品", coreTech: "光纤/光连接与高速互连，数据中心业务集中度高", globalSharePct: null, moat: "光纤连接技术 + 数据中心互连订单能见度高", altDifficulty: "STRONG", customers: "超大规模数据中心/电信", suppliers: "光纤预制棒/材料", competitors: "古河电工 · 住友电工 · Corning", growthDriver: "AI 数据中心光互连线缆/连接器需求", futureRisk: "客户集中 · 周期性 · 汇率", whyMatters: "AI 数据中心光互连能见度最高的日本标的", chainImpact: "AI 集群光互连核心", roadmap: [{ year: "2026", milestone: "数据中心互连持续放量", status: "进行中" }], investmentValue: { tech: 4, pos: 5, growth: 5, val: 3, risk: 3, rating: "BUY", conclusion: "AI 数据中心光互连主线，能见度高" }, segmentKeys: ["dc_network"], techKeys: ["optical_interconnect"], industryRole: "光互连主线龙头", benefitScore: 92,
      claims: [{ claimType: "GROWTH", statement: "フジクラ数据中心相关业务受 AI 集群光互连需求驱动高增长，被市场视为 AI 数据中心线缆主线（2025 领跑电线御三家）", confidence: "MID", importance: 8, evidence: [{ sourceTitle: "フジクラ 決算説明会資料", publisher: "Fujikura IR", sourceType: "EARNINGS", confidence: "MID", evidenceSummary: "公司披露数据中心业务高增长与订单能见度" }, { sourceTitle: "电线三社数据中心结构分析", publisher: "行业研究", sourceType: "INDUSTRY_REPORT", confidence: "MID", evidenceSummary: "フジクラ数据中心业务集中度与盈利能见度最高" }] }] },
    { companyKey: "furukawa_electric", symbol: "5801.T", name: "古河電気工業", nameZh: "古河电气工业", nameEn: "Furukawa Electric", country: "日本", market: "东证 Prime", listed: true, entityType: "COMPANY", coreProduct: "光纤/光缆、光器件、电力电缆", coreTech: "光纤与光器件，AI 数据中心互连", globalSharePct: null, moat: "光纤全产业链 + 光器件技术", altDifficulty: "STRONG", customers: "数据中心/电信/电力", suppliers: "光纤材料", competitors: "フジクラ · 住友电工 · Corning", growthDriver: "AI 数据中心光缆/光器件需求", futureRisk: "周期性 · 竞争 · 汇率", whyMatters: "光缆御三家，AI 数据中心互连受益（2026 被看好接棒）", chainImpact: "光互连供应", investmentValue: { tech: 4, pos: 4, growth: 5, val: 3, risk: 3, rating: "BUY", conclusion: "光缆御三家 AI 互连受益" }, segmentKeys: ["dc_network"], techKeys: ["optical_interconnect"], industryRole: "光缆御三家", benefitScore: 88,
      claims: [{ claimType: "GROWTH", statement: "古河电工光纤/光器件业务受 AI 数据中心互连需求驱动，被视为电线御三家 AI 主题的接力标的", confidence: "MID", importance: 7, evidence: [{ sourceTitle: "古河电工 決算説明会資料", publisher: "Furukawa IR", sourceType: "EARNINGS", confidence: "MID", evidenceSummary: "公司披露光纤/光器件受数据中心需求拉动" }] }] },
    { companyKey: "sumitomo_electric", symbol: "5802.T", name: "住友電気工業", nameZh: "住友电气工业", nameEn: "Sumitomo Electric Industries", country: "日本", market: "东证 Prime", listed: true, entityType: "COMPANY", coreProduct: "光纤/光缆、化合物半导体、汽车线束", coreTech: "光纤与光器件，业务多元", globalSharePct: null, moat: "光纤规模 + 多元业务分散", altDifficulty: "STRONG", customers: "数据中心/电信/汽车", suppliers: "材料", competitors: "フジクラ · 古河电工 · Corning", growthDriver: "AI 数据中心光缆需求（占比较分散）", futureRisk: "汽车业务周期 · 多元摊薄弹性", whyMatters: "光缆御三家中市值最大、业务最分散", chainImpact: "光互连供应", investmentValue: { tech: 4, pos: 4, growth: 4, val: 3, risk: 3, rating: "WATCH", conclusion: "光缆御三家·业务分散" }, segmentKeys: ["dc_network"], techKeys: ["optical_interconnect"], industryRole: "光缆御三家", benefitScore: 78 },
    { companyKey: "net_one", symbol: "7518.T", name: "ネットワンシステムズ", nameZh: "网一系统", nameEn: "Net One Systems", country: "日本", market: "东证 Prime", listed: true, entityType: "COMPANY", coreProduct: "网络集成、数据中心网络设计与构建", coreTech: "数据中心网络系统集成（Cisco/Arista/NVIDIA 网络）", globalSharePct: null, moat: "高端网络集成 Know-how + 大型客户", altDifficulty: "REPLACEABLE", customers: "运营商/企业/数据中心", suppliers: "Cisco · Arista · NVIDIA(Mellanox)", competitors: "伊藤忠 Techno · SCSK", growthDriver: "AI 数据中心网络建设与集成需求", futureRisk: "集成利润率 · 依赖海外设备", whyMatters: "AI 数据中心网络集成受益", chainImpact: "DC 网络集成", investmentValue: { tech: 3, pos: 4, growth: 4, val: 3, risk: 3, rating: "WATCH", conclusion: "DC 网络集成受益" }, segmentKeys: ["dc_network"], techKeys: ["dc_ethernet", "infiniband"], industryRole: "DC 网络集成", benefitScore: 70 },

    // ── 日本上市：算力硬件/载板 ──
    { companyKey: "ibiden", symbol: "4062.T", name: "イビデン", nameZh: "揖斐电", nameEn: "Ibiden", country: "日本", market: "东证 Prime", listed: true, entityType: "COMPANY", coreProduct: "高端 IC 封装载板（ABF）、陶瓷", coreTech: "大尺寸高多层 ABF 载板全球领先", globalSharePct: 25, moat: "高端 ABF 载板良率与产能壁垒，与顶级 AI 芯片厂深度绑定", altDifficulty: "NEAR_MONOPOLY", customers: "AI 芯片/CPU 大厂", suppliers: "ABF 材料", competitors: "新光电气 · AT&S · 欣兴", growthDriver: "AI 加速器大载板需求 · 玻璃基板演进", futureRisk: "客户高度集中 · 资本开支重 · 周期性", whyMatters: "AI 加速器封装上游关键载板，日本卡位", chainImpact: "AI 芯片封装上游", roadmap: [{ year: "2027", milestone: "玻璃基板研发", status: "研发" }], investmentValue: { tech: 5, pos: 5, growth: 4, val: 3, risk: 3, rating: "BUY", conclusion: "AI 载板上游领先，AI 芯片放量受益" }, segmentKeys: ["compute_hardware"], techKeys: ["ic_substrate"], industryRole: "ABF 载板领先", benefitScore: 84,
      claims: [{ claimType: "SHARE", statement: "Ibiden 在高端大尺寸 ABF 封装载板处于全球领先地位，是 AI 加速器/高端 CPU 封装的关键上游供应", confidence: "MID", importance: 8, evidence: [{ sourceTitle: "Ibiden 統合報告書/決算説明会", publisher: "イビデン IR", sourceType: "FILING", confidence: "MID", evidenceSummary: "公司披露高端 IC 载板领先地位与 AI 相关需求" }, { sourceTitle: "IC 载板行业报告", publisher: "行业研究机构", sourceType: "INDUSTRY_REPORT", confidence: "MID", evidenceSummary: "高端 ABF 载板由 Ibiden 等少数厂商主导" }] }] },
    { companyKey: "omron", symbol: "6645.T", name: "オムロン", nameZh: "欧姆龙", nameEn: "OMRON", country: "日本", market: "东证 Prime", listed: true, entityType: "COMPANY", coreProduct: "控制器件、继电器、电源控制部件", coreTech: "工业控制与继电器，供电/配电用元件", globalSharePct: null, moat: "继电器与控制元件品牌", altDifficulty: "REPLACEABLE", customers: "电源/配电/工业设备", suppliers: "电子元件", competitors: "松下 · 富士通元件", growthDriver: "数据中心供电元件需求（间接）", futureRisk: "工控周期 · 关联度较弱", whyMatters: "供电/配电用控制元件间接受益", chainImpact: "供电元件供应", investmentValue: { tech: 3, pos: 3, growth: 3, val: 3, risk: 3, rating: "WATCH", conclusion: "供电元件间接受益" }, segmentKeys: ["power_infra"], techKeys: ["power_distribution"], industryRole: "供电元件（间接）", benefitScore: 58 },

    // ── 日本上市：服务器/系统 ──
    { companyKey: "nec", symbol: "6701.T", name: "日本電気", nameZh: "日本电气 NEC", nameEn: "NEC", country: "日本", market: "东证 Prime", listed: true, entityType: "COMPANY", coreProduct: "服务器、数据中心、网络、生成式 AI 平台", coreTech: "IT 系统集成与服务器，数据中心与 AI 平台", globalSharePct: null, moat: "日本 IT 系统集成与政企客户基础", altDifficulty: "REPLACEABLE", customers: "政企/电信/公共", suppliers: "半导体/整机", competitors: "富士通 · 日立 · 海外云", growthDriver: "生成式 AI 平台 · 数据中心与 IT 服务需求", futureRisk: "硬件利润率 · 云竞争", whyMatters: "日本 IT/数据中心系统主力", chainImpact: "服务器与 IT 服务", investmentValue: { tech: 4, pos: 4, growth: 4, val: 3, risk: 3, rating: "WATCH", conclusion: "IT/DC 系统主力受益" }, segmentKeys: ["server_system", "dc_facility"], techKeys: ["ai_server", "cloud_infra"], industryRole: "IT/DC 系统主力", benefitScore: 74 },
    { companyKey: "fujitsu", symbol: "6702.T", name: "富士通", nameZh: "富士通", nameEn: "Fujitsu", country: "日本", market: "东证 Prime", listed: true, entityType: "COMPANY", coreProduct: "服务器（PRIMERGY）、超算、云、IT 服务", coreTech: "服务器与超算（富岳），生成式 AI 与云", globalSharePct: null, moat: "超算/HPC 技术积累 + 政企 IT 服务", altDifficulty: "REPLACEABLE", customers: "政企/科研/公共", suppliers: "半导体/整机", competitors: "NEC · 日立 · 海外云", growthDriver: "生成式 AI · 超算/HPC · 云与 IT 服务", futureRisk: "硬件利润率 · 云竞争", whyMatters: "服务器/超算与 AI 平台主力", chainImpact: "服务器/HPC 与 IT 服务", investmentValue: { tech: 4, pos: 4, growth: 4, val: 3, risk: 3, rating: "WATCH", conclusion: "服务器/HPC/AI 平台受益" }, segmentKeys: ["server_system", "hyperscale_cloud"], techKeys: ["ai_server", "cloud_infra"], industryRole: "服务器/HPC 主力", benefitScore: 74 },
    { companyKey: "hitachi", symbol: "6501.T", name: "日立製作所", nameZh: "日立制作所", nameEn: "Hitachi", country: "日本", market: "东证 Prime", listed: true, entityType: "COMPANY", coreProduct: "IT/OT、数据中心、电网设备（日立能源变压器/输配电）", coreTech: "IT 与电网/重电综合（Hitachi Energy），数据中心 IT 与供电双卡位", globalSharePct: null, moat: "IT×电网双能力，Hitachi Energy 全球电网设备领先", altDifficulty: "STRONG", customers: "电网/数据中心/工业/政企", suppliers: "全球供应链", competitors: "三菱电机 · 施耐德 · GE Vernova", growthDriver: "数据中心 IT + 电网变压器/输配电需求（AI 供电瓶颈）", futureRisk: "重电交付周期 · 综合集团折价", whyMatters: "同时受益数据中心 IT 与电网供电扩容", chainImpact: "IT 与电网供电双线", investmentValue: { tech: 4, pos: 5, growth: 4, val: 3, risk: 3, rating: "BUY", conclusion: "IT×电网双卡位，AI 供电瓶颈受益" }, segmentKeys: ["server_system", "power_infra"], techKeys: ["transformer", "cloud_infra"], industryRole: "IT×电网双卡位", benefitScore: 82,
      claims: [{ claimType: "MOAT", statement: "日立通过 Hitachi Energy 在全球电网/输配电与变压器设备处于领先，叠加 IT/数据中心能力，双线受益 AI 数据中心供电瓶颈", confidence: "MID", importance: 8, evidence: [{ sourceTitle: "日立 統合報告書/決算説明会", publisher: "Hitachi IR", sourceType: "FILING", confidence: "MID", evidenceSummary: "公司披露 Hitachi Energy 电网业务与数据中心相关成长" }] }] },

    // ── 日本上市：超大规模/云/DC 运营 ──
    { companyKey: "ntt", symbol: "9432.T", name: "日本電信電話", nameZh: "日本电信电话 NTT", nameEn: "NTT", country: "日本", market: "东证 Prime", listed: true, entityType: "COMPANY", coreProduct: "NTT Global Data Centers、电信、云、IOWN", coreTech: "全球顶级数据中心运营商之一，IOWN 全光网络", globalSharePct: null, moat: "全球数据中心规模 + 电信基础设施 + IOWN 光技术", altDifficulty: "STRONG", customers: "超大规模/企业/政企", suppliers: "设备/电力", competitors: "Equinix · Digital Realty · 海外云", growthDriver: "全球数据中心扩建 · AI 需求 · IOWN", futureRisk: "资本开支重 · 电力约束 · 监管", whyMatters: "日本最大数据中心运营主力，全球布局", chainImpact: "数据中心运营总枢纽（JP）", roadmap: [{ year: "2026", milestone: "IOWN/数据中心扩建", status: "进行中" }], investmentValue: { tech: 4, pos: 5, growth: 4, val: 4, risk: 2, rating: "BUY", conclusion: "全球 DC 运营主力，AI 需求受益" }, segmentKeys: ["hyperscale_cloud", "dc_facility"], techKeys: ["cloud_infra", "edge_datacenter"], industryRole: "DC 运营总枢纽", benefitScore: 84,
      claims: [{ claimType: "SHARE", statement: "NTT 通过 NTT Global Data Centers 位列全球顶级数据中心运营商之一，AI 需求带动全球扩建", confidence: "MID", importance: 8, evidence: [{ sourceTitle: "NTT 統合報告書/官网", publisher: "NTT IR", sourceType: "FILING", confidence: "MID", evidenceSummary: "公司披露全球数据中心业务规模与扩建计划" }] }] },
    { companyKey: "kddi", symbol: "9433.T", name: "KDDI", nameZh: "KDDI", nameEn: "KDDI", country: "日本", market: "东证 Prime", listed: true, entityType: "COMPANY", coreProduct: "TELEHOUSE 数据中心、电信、云", coreTech: "全球托管数据中心（TELEHOUSE）与电信云", globalSharePct: null, moat: "TELEHOUSE 全球托管网络 + 电信基础设施", altDifficulty: "STRONG", customers: "企业/金融/超大规模", suppliers: "设备/电力", competitors: "Equinix · NTT · 海外托管商", growthDriver: "AI 数据中心托管与云需求", futureRisk: "资本开支 · 电力约束", whyMatters: "全球托管数据中心日本主力", chainImpact: "托管数据中心运营", investmentValue: { tech: 4, pos: 4, growth: 4, val: 4, risk: 2, rating: "WATCH", conclusion: "TELEHOUSE 托管受益" }, segmentKeys: ["hyperscale_cloud", "dc_facility"], techKeys: ["cloud_infra"], industryRole: "托管 DC 主力", benefitScore: 76 },
    { companyKey: "softbank_corp", symbol: "9434.T", name: "ソフトバンク", nameZh: "软银", nameEn: "SoftBank Corp", country: "日本", market: "东证 Prime", listed: true, entityType: "COMPANY", coreProduct: "电信、云、AI 数据中心（与 NVIDIA 合作、堺 AI DC）", coreTech: "生成式 AI 基础设施与国内 AI 算力布局", globalSharePct: null, moat: "电信+AI 战略 + 大规模 GPU 采购与 AI DC 建设", altDifficulty: "REPLACEABLE", customers: "企业/消费者/AI 用户", suppliers: "NVIDIA · 设备商", competitors: "NTT · KDDI · 海外云", growthDriver: "国内 AI 算力/数据中心建设（堺等）", futureRisk: "投资回报不确定 · 电力/资本开支", whyMatters: "日本本土 AI 算力与数据中心建设先锋", chainImpact: "AI 算力与云建设", roadmap: [{ year: "2026", milestone: "国内 AI 数据中心建设", status: "进行中" }], investmentValue: { tech: 4, pos: 4, growth: 4, val: 3, risk: 3, rating: "WATCH", conclusion: "本土 AI 算力建设受益" }, segmentKeys: ["hyperscale_cloud"], techKeys: ["cloud_infra", "ai_server"], industryRole: "本土 AI 算力先锋", benefitScore: 78 },
    { companyKey: "ntt_data", symbol: "9613.T", name: "NTTデータグループ", nameZh: "NTT数据集团", nameEn: "NTT DATA Group", country: "日本", market: "东证 Prime", listed: true, entityType: "COMPANY", coreProduct: "IT 服务、系统集成、数据中心与云", coreTech: "全球 IT 服务与数据中心运营", globalSharePct: null, moat: "全球 IT 服务规模 + 政企客户", altDifficulty: "REPLACEABLE", customers: "政企/金融/公共", suppliers: "设备/云", competitors: "埃森哲 · 富士通 · 海外集成商", growthDriver: "生成式 AI 集成 · 数据中心与云服务", futureRisk: "利润率 · 竞争", whyMatters: "全球 IT 服务与数据中心受益", chainImpact: "IT 服务与 DC 运营", investmentValue: { tech: 3, pos: 4, growth: 4, val: 3, risk: 3, rating: "WATCH", conclusion: "IT 服务/DC 受益" }, segmentKeys: ["hyperscale_cloud", "dc_facility"], techKeys: ["cloud_infra"], industryRole: "IT 服务/DC", benefitScore: 72 },
    { companyKey: "sakura_internet", symbol: "3778.T", name: "さくらインターネット", nameZh: "樱花互联网", nameEn: "Sakura Internet", country: "日本", market: "东证 Prime", listed: true, entityType: "COMPANY", coreProduct: "GPU 云、数据中心、托管服务器", coreTech: "国产 GPU 云平台（政策支持的日本 AI 云）", globalSharePct: null, moat: "本土 GPU 云先发 + 政策/经产省支持", altDifficulty: "REPLACEABLE", customers: "AI 开发者/企业/政府", suppliers: "NVIDIA · 数据中心设备", competitors: "海外云 · NTT · 软银", growthDriver: "日本主权 AI 云与 GPU 算力需求", futureRisk: "GPU 采购/摊销 · 竞争 · 估值高", whyMatters: "日本纯 GPU 云稀缺标的，AI 算力主题弹性大", chainImpact: "本土 GPU 云供给", roadmap: [{ year: "2026", milestone: "GPU 云扩容", status: "进行中" }], investmentValue: { tech: 4, pos: 4, growth: 5, val: 2, risk: 4, rating: "WATCH", conclusion: "本土 GPU 云弹性标的·估值偏高" }, segmentKeys: ["hyperscale_cloud", "server_system"], techKeys: ["cloud_infra", "ai_server"], industryRole: "本土 GPU 云", benefitScore: 80, isHiddenChampion: true,
      hiddenChampion: { score: 78, dimensions: { nicheRank: 88, techUnique: 65, globalShare: 30, jpShare: 80, altDifficulty: 55, stickiness: 70, margin: 55, growth: 92, marketCap: 45, importance: 85, competitors: 60, overseasRev: 25 }, verdict: "CANDIDATE", reasons: "日本稀缺纯 GPU 云平台，受主权 AI 云政策支持，AI 算力需求弹性大", mainRisk: "GPU 采购与摊销压力、估值偏高、竞争加剧", watchlistCandidate: true },
      claims: [{ claimType: "GROWTH", statement: "さくらインターネット作为日本本土 GPU 云先发者，受主权 AI 云政策支持，算力需求高增长", confidence: "MID", importance: 7, evidence: [{ sourceTitle: "さくらインターネット 決算説明会/官网", publisher: "Sakura Internet IR", sourceType: "EARNINGS", confidence: "MID", evidenceSummary: "公司披露 GPU 云业务扩张与政策支持" }] }] },
    { companyKey: "iij", symbol: "3774.T", name: "インターネットイニシアティブ", nameZh: "IIJ", nameEn: "Internet Initiative Japan", country: "日本", market: "东证 Prime", listed: true, entityType: "COMPANY", coreProduct: "网络服务、云、数据中心", coreTech: "网络与云基础设施服务", globalSharePct: null, moat: "老牌网络/云服务品牌与企业客户", altDifficulty: "REPLACEABLE", customers: "企业/政企", suppliers: "设备/网络", competitors: "NTT · KDDI · 海外云", growthDriver: "企业云与网络需求 · AI 相关", futureRisk: "竞争 · 利润率", whyMatters: "网络/云基础设施受益", chainImpact: "网络与云服务", investmentValue: { tech: 3, pos: 3, growth: 3, val: 3, risk: 3, rating: "WATCH", conclusion: "网络/云稳健受益" }, segmentKeys: ["hyperscale_cloud", "dc_network"], techKeys: ["cloud_infra"], industryRole: "网络/云服务", benefitScore: 64 },

    // ── 海外/未上市（listed=false, symbol=null, benefitScore=0）──
    { companyKey: "nvidia", name: "NVIDIA", nameZh: "英伟达", nameEn: "NVIDIA", country: "美国", listed: false, entityType: "FOREIGN", coreProduct: "AI GPU/加速器、NVLink、InfiniBand、Spectrum-X、机架级系统", coreTech: "AI 训练/推理加速近乎垄断 + 网络（Mellanox）+ 机架级架构", globalSharePct: 90, moat: "CUDA 生态 + 全栈（芯片/网络/系统/软件），后来者难越", altDifficulty: "MONOPOLY", customers: "超大规模/云/企业/GPU 云", suppliers: "TSMC · Ibiden(载板) · HBM 存储 · 光互连", competitors: "AMD · 自研 ASIC · Broadcom", growthDriver: "AI 训练/推理算力需求", futureRisk: "出口管制 · 自研 ASIC 替代 · 集中度", whyMatters: "AI 数据中心的算力总引擎，拉动散热/供电/网络/载板全链（日本上游受益）", chainImpact: "AI 算力总引擎（海外）", segmentKeys: ["compute_hardware", "server_system", "dc_network"], techKeys: ["ai_server", "rack_scale", "infiniband", "dc_ethernet"], industryRole: "算力总引擎·海外", benefitScore: 0,
      claims: [{ claimType: "CHOKEPOINT", statement: "NVIDIA 在 AI 训练加速器近乎垄断（约九成），并以 CUDA 生态与网络/机架级全栈构成 AI 数据中心的核心卡脖子", confidence: "HIGH", importance: 10, evidence: [{ sourceTitle: "NVIDIA Form 10-K / 官方资料", publisher: "NVIDIA", sourceType: "FILING", confidence: "HIGH", evidenceSummary: "公司披露数据中心 GPU 主导地位与全栈战略" }, { sourceTitle: "AI 加速器市场报告", publisher: "行业研究机构", sourceType: "INDUSTRY_REPORT", confidence: "HIGH", evidenceSummary: "NVIDIA 主导 AI 训练 GPU 市场" }] }] },
    { companyKey: "amd", name: "AMD", nameZh: "AMD", nameEn: "AMD", country: "美国", listed: false, entityType: "FOREIGN", coreProduct: "Instinct GPU(MI 系列)、EPYC CPU", coreTech: "AI GPU 与服务器 CPU 挑战者", globalSharePct: null, moat: "CPU/GPU 双线 + 开放软件栈 ROCm", altDifficulty: "STRONG", customers: "云/超大规模", suppliers: "TSMC · 载板 · HBM", competitors: "NVIDIA · Intel", growthDriver: "AI GPU 份额争夺 · EPYC 服务器", futureRisk: "软件生态弱于 CUDA", whyMatters: "AI 加速与服务器 CPU 第二供应", chainImpact: "算力硬件（海外）", segmentKeys: ["compute_hardware"], techKeys: ["ai_server"], industryRole: "算力挑战者·海外", benefitScore: 0 },
    { companyKey: "intel", name: "Intel", nameZh: "英特尔", nameEn: "Intel", country: "美国", listed: false, entityType: "FOREIGN", coreProduct: "Xeon CPU、Gaudi 加速器", coreTech: "服务器 CPU 主力，AI 加速追赶", globalSharePct: null, moat: "服务器 CPU 存量 + x86 生态", altDifficulty: "STRONG", customers: "云/企业", suppliers: "自有晶圆/代工", competitors: "AMD · NVIDIA · Arm 服务器", growthDriver: "服务器 CPU · Gaudi 加速", futureRisk: "AI 加速落后 · 制程追赶", whyMatters: "数据中心 CPU 主力", chainImpact: "算力硬件（海外）", segmentKeys: ["compute_hardware"], techKeys: ["ai_server"], industryRole: "服务器 CPU·海外", benefitScore: 0 },
    { companyKey: "broadcom", name: "Broadcom", nameZh: "博通", nameEn: "Broadcom", country: "美国", listed: false, entityType: "FOREIGN", coreProduct: "交换芯片(Tomahawk/Jericho)、定制 AI ASIC、光器件", coreTech: "商用交换硅与定制 AI ASIC 领先", globalSharePct: null, moat: "商用交换芯片主导 + 超大规模定制 ASIC 深绑", altDifficulty: "NEAR_MONOPOLY", customers: "交换机厂商/超大规模", suppliers: "TSMC", competitors: "Marvell · NVIDIA · Cisco Silicon One", growthDriver: "AI 后端网以太网 · 定制 ASIC", futureRisk: "客户自研 · 集中度", whyMatters: "AI 数据中心网络与定制算力关键（海外卡位）", chainImpact: "网络芯片/定制 ASIC（海外）", segmentKeys: ["dc_network", "compute_hardware"], techKeys: ["dc_ethernet"], industryRole: "网络芯片龙头·海外", benefitScore: 0,
      claims: [{ claimType: "CHOKEPOINT", statement: "Broadcom 在数据中心商用交换芯片处于主导地位，并为超大规模厂商定制 AI ASIC，是 AI 网络与定制算力的关键节点", confidence: "MID", importance: 8, evidence: [{ sourceTitle: "Broadcom 官方资料 / 行业报告", publisher: "Broadcom", sourceType: "FILING", confidence: "MID", evidenceSummary: "公司披露交换芯片与定制 AI ASIC 业务" }] }] },
    { companyKey: "arista", name: "Arista Networks", nameZh: "Arista", nameEn: "Arista Networks", country: "美国", listed: false, entityType: "FOREIGN", coreProduct: "数据中心以太网交换机", coreTech: "高性能低时延 DC 以太网交换与 EOS 软件", globalSharePct: null, moat: "超大规模数据中心以太网份额领先 + 软件栈", altDifficulty: "STRONG", customers: "超大规模/云", suppliers: "Broadcom(交换芯片)", competitors: "Cisco · NVIDIA · 白牌", growthDriver: "AI 后端网以太网建设", futureRisk: "客户集中 · 白牌竞争", whyMatters: "AI 集群以太网交换核心", chainImpact: "DC 网络（海外）", segmentKeys: ["dc_network"], techKeys: ["dc_ethernet"], industryRole: "DC 以太网龙头·海外", benefitScore: 0 },
    { companyKey: "cisco", name: "Cisco", nameZh: "思科", nameEn: "Cisco", country: "美国", listed: false, entityType: "FOREIGN", coreProduct: "网络设备、Silicon One、数据中心交换", coreTech: "综合网络设备与自研交换硅", globalSharePct: null, moat: "网络设备存量与生态", altDifficulty: "STRONG", customers: "企业/运营商/云", suppliers: "自研+外购芯片", competitors: "Arista · NVIDIA · 华为", growthDriver: "AI 数据中心网络", futureRisk: "云自研/白牌", whyMatters: "数据中心网络主力之一", chainImpact: "DC 网络（海外）", segmentKeys: ["dc_network"], techKeys: ["dc_ethernet"], industryRole: "网络综合·海外", benefitScore: 0 },
    { companyKey: "dell", name: "Dell Technologies", nameZh: "戴尔", nameEn: "Dell Technologies", country: "美国", listed: false, entityType: "FOREIGN", coreProduct: "AI 服务器、存储", coreTech: "企业级 AI 服务器整机与集成", globalSharePct: null, moat: "企业渠道与供应链规模", altDifficulty: "STRONG", customers: "企业/云/主权", suppliers: "NVIDIA · 组件", competitors: "Supermicro · HPE · 白牌", growthDriver: "AI 服务器出货", futureRisk: "利润率薄 · 白牌竞争", whyMatters: "AI 服务器整机主力", chainImpact: "服务器整机（海外）", segmentKeys: ["server_system"], techKeys: ["ai_server"], industryRole: "AI 服务器·海外", benefitScore: 0 },
    { companyKey: "supermicro", name: "Super Micro Computer", nameZh: "超微", nameEn: "Supermicro", country: "美国", listed: false, entityType: "FOREIGN", coreProduct: "AI 服务器、液冷机架方案", coreTech: "高密度 AI 服务器与液冷整机快速交付", globalSharePct: null, moat: "AI 服务器+液冷一体化与上市速度", altDifficulty: "STRONG", customers: "云/超大规模/企业", suppliers: "NVIDIA · 组件", competitors: "Dell · HPE · 台系 ODM", growthDriver: "AI 服务器+液冷放量", futureRisk: "利润率 · 治理 · 竞争", whyMatters: "AI 服务器+液冷整机代表", chainImpact: "服务器/液冷整机（海外）", segmentKeys: ["server_system", "cooling"], techKeys: ["ai_server", "liquid_cooling"], industryRole: "AI 服务器+液冷·海外", benefitScore: 0 },
    { companyKey: "hpe", name: "HPE", nameZh: "慧与", nameEn: "Hewlett Packard Enterprise", country: "美国", listed: false, entityType: "FOREIGN", coreProduct: "服务器、超算(Cray)、AI 系统", coreTech: "企业服务器与超算/HPC", globalSharePct: null, moat: "超算/HPC 与企业存量", altDifficulty: "STRONG", customers: "企业/科研/主权", suppliers: "NVIDIA · 组件", competitors: "Dell · Supermicro", growthDriver: "AI/超算系统", futureRisk: "利润率 · 竞争", whyMatters: "AI/超算系统主力", chainImpact: "服务器/超算（海外）", segmentKeys: ["server_system"], techKeys: ["ai_server"], industryRole: "服务器/超算·海外", benefitScore: 0 },
    { companyKey: "vertiv", name: "Vertiv", nameZh: "Vertiv", nameEn: "Vertiv", country: "美国", listed: false, entityType: "FOREIGN", coreProduct: "数据中心热管理（液冷/风冷）、UPS、供电", coreTech: "数据中心供电与散热全套解决方案", globalSharePct: null, moat: "供电+散热一体化 + 全球服务网络", altDifficulty: "STRONG", customers: "超大规模/托管", suppliers: "组件/设备", competitors: "施耐德 · Eaton · 高砂热学(区域)", growthDriver: "AI 数据中心液冷与供电需求", futureRisk: "周期性 · 竞争", whyMatters: "AI 数据中心供电+散热海外龙头，与日本厂商竞合", chainImpact: "供电+散热（海外）", segmentKeys: ["cooling", "power_infra"], techKeys: ["liquid_cooling", "ups_backup", "power_distribution"], industryRole: "供电+散热龙头·海外", benefitScore: 0,
      claims: [{ claimType: "SHARE", statement: "Vertiv 在数据中心热管理与关键供电处于全球领先，AI 液冷需求驱动高增长", confidence: "MID", importance: 7, evidence: [{ sourceTitle: "Vertiv 官方资料 / 行业报告", publisher: "Vertiv", sourceType: "FILING", confidence: "MID", evidenceSummary: "公司披露数据中心供电与散热业务及 AI 需求" }] }] },
    { companyKey: "schneider", name: "Schneider Electric", nameZh: "施耐德电气", nameEn: "Schneider Electric", country: "法国", listed: false, entityType: "FOREIGN", coreProduct: "数据中心供配电、UPS、冷却与管理软件", coreTech: "配电+UPS+散热+软件全套", globalSharePct: null, moat: "全球配电与数据中心解决方案规模", altDifficulty: "STRONG", customers: "超大规模/托管/企业", suppliers: "组件", competitors: "Vertiv · Eaton · 富士电机(区域)", growthDriver: "AI 数据中心供电与冷却", futureRisk: "周期性", whyMatters: "数据中心供电+冷却海外龙头", chainImpact: "供配电+冷却（海外）", segmentKeys: ["power_infra", "cooling"], techKeys: ["power_distribution", "ups_backup"], industryRole: "供配电龙头·海外", benefitScore: 0 },
    { companyKey: "eaton", name: "Eaton", nameZh: "伊顿", nameEn: "Eaton", country: "美国", listed: false, entityType: "FOREIGN", coreProduct: "电源管理、UPS、配电", coreTech: "电源管理与配电设备", globalSharePct: null, moat: "电气产品规模与渠道", altDifficulty: "STRONG", customers: "数据中心/工业", suppliers: "组件", competitors: "施耐德 · Vertiv", growthDriver: "数据中心供电需求", futureRisk: "周期性", whyMatters: "数据中心供电海外主力", chainImpact: "供电（海外）", segmentKeys: ["power_infra"], techKeys: ["power_distribution", "ups_backup"], industryRole: "电源管理·海外", benefitScore: 0 },
    { companyKey: "equinix", name: "Equinix", nameZh: "Equinix", nameEn: "Equinix", country: "美国", listed: false, entityType: "FOREIGN", coreProduct: "全球托管数据中心（REIT）", coreTech: "全球互连托管数据中心平台", globalSharePct: null, moat: "全球互连生态与规模（托管龙头）", altDifficulty: "STRONG", customers: "企业/云/网络", suppliers: "设备/电力", competitors: "Digital Realty · NTT · KDDI", growthDriver: "AI 数据中心托管与互连", futureRisk: "电力约束 · 资本开支", whyMatters: "全球托管数据中心龙头（海外对标 NTT/KDDI）", chainImpact: "托管数据中心（海外）", segmentKeys: ["dc_facility"], techKeys: ["edge_datacenter"], industryRole: "托管 DC 龙头·海外", benefitScore: 0,
      claims: [{ claimType: "SHARE", statement: "Equinix 为全球互连托管数据中心龙头，AI 需求带动扩建", confidence: "MID", importance: 7, evidence: [{ sourceTitle: "Equinix Form 10-K / 官方资料", publisher: "Equinix", sourceType: "FILING", confidence: "MID", evidenceSummary: "公司披露全球托管数据中心规模与 AI 需求" }] }] },
    { companyKey: "digital_realty", name: "Digital Realty", nameZh: "Digital Realty", nameEn: "Digital Realty", country: "美国", listed: false, entityType: "FOREIGN", coreProduct: "超大规模/托管数据中心（REIT）", coreTech: "超大规模数据中心开发与运营", globalSharePct: null, moat: "超大规模数据中心土地与电力资源", altDifficulty: "STRONG", customers: "超大规模/企业", suppliers: "设备/电力", competitors: "Equinix · NTT", growthDriver: "AI 数据中心扩建", futureRisk: "电力约束 · 资本开支", whyMatters: "超大规模托管数据中心海外龙头", chainImpact: "托管数据中心（海外）", segmentKeys: ["dc_facility"], techKeys: ["edge_datacenter"], industryRole: "超大规模 DC·海外", benefitScore: 0 },
    { companyKey: "microsoft", name: "Microsoft", nameZh: "微软", nameEn: "Microsoft", country: "美国", listed: false, entityType: "FOREIGN", coreProduct: "Azure 云、AI 数据中心", coreTech: "超大规模云与 AI 基础设施", globalSharePct: null, moat: "Azure 生态 + OpenAI 合作 + 资本开支", altDifficulty: "STRONG", customers: "企业/开发者/消费者", suppliers: "NVIDIA · 设备商 · 电力", competitors: "AWS · Google Cloud", growthDriver: "AI 云与数据中心资本开支", futureRisk: "算力/电力供给 · 回报", whyMatters: "AI 数据中心总需求方之一，采购拉动全链（含日本上游）", chainImpact: "超大规模需求方（海外）", segmentKeys: ["hyperscale_cloud"], techKeys: ["cloud_infra"], industryRole: "超大规模云·海外", benefitScore: 0 },
    { companyKey: "aws", name: "Amazon Web Services", nameZh: "亚马逊 AWS", nameEn: "Amazon AWS", country: "美国", listed: false, entityType: "FOREIGN", coreProduct: "AWS 云、自研芯片(Trainium/Inferentia)、AI 数据中心", coreTech: "超大规模云与自研 AI 芯片", globalSharePct: null, moat: "云市场份额领先 + 自研芯片", altDifficulty: "STRONG", customers: "企业/开发者", suppliers: "NVIDIA · 自研 · 设备商", competitors: "Azure · Google Cloud", growthDriver: "AI 云资本开支 · 自研芯片", futureRisk: "算力/电力 · 回报", whyMatters: "AI 数据中心最大需求方之一", chainImpact: "超大规模需求方（海外）", segmentKeys: ["hyperscale_cloud"], techKeys: ["cloud_infra"], industryRole: "超大规模云·海外", benefitScore: 0 },
    { companyKey: "google_cloud", name: "Google Cloud", nameZh: "谷歌云", nameEn: "Google Cloud", country: "美国", listed: false, entityType: "FOREIGN", coreProduct: "Google Cloud、TPU、AI 数据中心", coreTech: "超大规模云与自研 TPU", globalSharePct: null, moat: "自研 TPU + AI 研究 + 云生态", altDifficulty: "STRONG", customers: "企业/开发者", suppliers: "Broadcom(TPU) · NVIDIA · 设备商", competitors: "Azure · AWS", growthDriver: "AI 云与自研 TPU 扩张", futureRisk: "算力/电力 · 回报", whyMatters: "AI 数据中心需求方 + 自研 ASIC 拉动 Broadcom", chainImpact: "超大规模需求方（海外）", segmentKeys: ["hyperscale_cloud"], techKeys: ["cloud_infra"], industryRole: "超大规模云·海外", benefitScore: 0 },
    { companyKey: "meta", name: "Meta", nameZh: "Meta", nameEn: "Meta", country: "美国", listed: false, entityType: "FOREIGN", coreProduct: "AI 数据中心、自研 MTIA 芯片", coreTech: "超大规模 AI 训练集群与自研加速", globalSharePct: null, moat: "巨额资本开支 + 自研芯片 + 开源模型", altDifficulty: "STRONG", customers: "自用（广告/AI）", suppliers: "NVIDIA · 设备商 · 电力", competitors: "其它超大规模", growthDriver: "AI 训练集群大规模自建", futureRisk: "回报不确定 · 电力", whyMatters: "AI 数据中心巨额自建需求方", chainImpact: "超大规模需求方（海外）", segmentKeys: ["hyperscale_cloud"], techKeys: ["cloud_infra", "ai_server"], industryRole: "超大规模自建·海外", benefitScore: 0 },
  ],

  bottlenecks: [
    { name: "AI 加速器（GPU）供给", dims: { concentration: 92, altDifficulty: 85, certCycle: 60, capacityExpand: 55, switchCost: 90, supplyConcentration: 90, geopolitical: 85, patent: 85, talent: 80, capital: 80 }, level: "CRITICAL", whyBottleneck: "AI 训练算力由 NVIDIA 近乎垄断，CUDA 生态与供给分配是全链起点", controlledBy: "NVIDIA（海外）", dependents: "所有 AI 数据中心/云", hasAlternative: "AMD/自研 ASIC（生态弱）", jpBeneficiary: "上游载板 Ibiden、光互连/散热/供电配套受益", jpSymbols: ["4062.T"], triggers: "出口管制/自研 ASIC 替代/产能变化",
      claims: [{ claimType: "CHOKEPOINT", statement: "AI 加速器由 NVIDIA 近乎垄断，是 AI 数据中心算力的 CRITICAL 级卡脖子，日本在其封装载板/光互连/散热/供电环节受益", confidence: "HIGH", importance: 10, evidence: [{ sourceTitle: "AI 加速器市场报告", publisher: "行业研究机构", sourceType: "INDUSTRY_REPORT", confidence: "HIGH", evidenceSummary: "NVIDIA 主导 AI 训练 GPU 市场" }] }] },
    { name: "数据中心电力供给", dims: { concentration: 70, altDifficulty: 80, certCycle: 85, capacityExpand: 40, switchCost: 75, supplyConcentration: 65, geopolitical: 55, patent: 50, talent: 70, capital: 88 }, level: "CRITICAL", whyBottleneck: "电网接入、变压器交期与供电容量成为 AI 数据中心扩张的真正物理卡点", controlledBy: "电网/重电设备商（日立能源/三菱电机/富士电机）", dependents: "所有 AI 数据中心", hasAlternative: "自备发电/储能（部分缓解）", jpBeneficiary: "变压器/UPS/配电/施工受益", jpSymbols: ["6501.T", "6503.T", "6504.T", "1942.T"], triggers: "变压器产能与电网扩容进度",
      claims: [{ claimType: "CHOKEPOINT", statement: "电力供给（电网接入、变压器交期、供电容量）是 AI 数据中心扩张的真正卡点，日本重电/UPS/配电/施工厂商受益", confidence: "MID", importance: 9, evidence: [{ sourceTitle: "数据中心电力/电网设备行业报告", publisher: "行业研究机构", sourceType: "INDUSTRY_REPORT", confidence: "MID", evidenceSummary: "电力与变压器供给制约数据中心建设" }] }] },
    { name: "高密度散热（液冷）", dims: { concentration: 60, altDifficulty: 65, certCycle: 55, capacityExpand: 60, switchCost: 70, supplyConcentration: 55, geopolitical: 30, patent: 60, talent: 65, capital: 55 }, level: "HIGH", whyBottleneck: "AI 机架功率密度突破风冷极限，液冷交付与运维能力成瓶颈", controlledBy: "Vertiv/施耐德/Supermicro + 日本高砂热学/ニデック", dependents: "高密度 AI 数据中心", hasAlternative: "高效风冷（能力有限）", jpBeneficiary: "散热工程与液冷组件受益", jpSymbols: ["1969.T", "6594.T", "1961.T"], triggers: "液冷标准化与产能" },
    { name: "AI 集群光互连", dims: { concentration: 62, altDifficulty: 60, certCycle: 55, capacityExpand: 60, switchCost: 65, supplyConcentration: 58, geopolitical: 40, patent: 65, talent: 60, capital: 55 }, level: "HIGH", whyBottleneck: "大规模 AI 集群内外高速光互连线缆/连接器需求激增，供给集中于少数厂商", controlledBy: "古河/フジクラ/住友电工 + Corning", dependents: "AI 训练/推理集群", hasAlternative: "铜缆 DAC/AEC（短距）", jpBeneficiary: "光缆御三家直接受益", jpSymbols: ["5801.T", "5803.T", "5802.T"], triggers: "CPO 商用与光缆产能" },
    { name: "高端 IC 封装载板（ABF）", dims: { concentration: 75, altDifficulty: 78, certCycle: 80, capacityExpand: 50, switchCost: 80, supplyConcentration: 72, geopolitical: 45, patent: 78, talent: 70, capital: 70 }, level: "HIGH", whyBottleneck: "AI 加速器大尺寸高多层 ABF 载板产能/良率受限，供给集中", controlledBy: "Ibiden/新光电气/AT&S/欣兴", dependents: "AI 加速器封装", hasAlternative: "玻璃基板（研发中）", jpBeneficiary: "Ibiden 卡位受益", jpSymbols: ["4062.T"], triggers: "AI 芯片大载板产能与玻璃基板导入" },
  ],

  edges: [
    // 供应链纵向（上游→中游→下游/基础设施）
    { fromType: "SEGMENT", fromKey: "compute_hardware", toType: "SEGMENT", toKey: "server_system", edgeType: "SUPPLY", strength: 95, note: "算力芯片/载板 → AI 服务器整机" },
    { fromType: "SEGMENT", fromKey: "server_system", toType: "SEGMENT", toKey: "dc_facility", edgeType: "DEPEND", strength: 85, note: "服务器整机部署于数据中心设施" },
    { fromType: "SEGMENT", fromKey: "cooling", toType: "SEGMENT", toKey: "server_system", edgeType: "SUPPLY", strength: 85, note: "散热/液冷保障高密度服务器运行" },
    { fromType: "SEGMENT", fromKey: "power_infra", toType: "SEGMENT", toKey: "dc_facility", edgeType: "SUPPLY", strength: 90, note: "供配电/UPS/变压器支撑数据中心设施" },
    { fromType: "SEGMENT", fromKey: "dc_network", toType: "SEGMENT", toKey: "server_system", edgeType: "SUPPLY", strength: 80, note: "网络/光互连连接服务器集群" },
    { fromType: "SEGMENT", fromKey: "hyperscale_cloud", toType: "SEGMENT", toKey: "server_system", edgeType: "CUSTOMER", strength: 90, note: "超大规模云是服务器/整机的总需求方" },
    // 公司 → 环节
    { fromType: "COMPANY", fromKey: "nvidia", toType: "SEGMENT", toKey: "server_system", edgeType: "SUPPLY", strength: 95, note: "NVIDIA GPU/系统供 AI 服务器" },
    { fromType: "COMPANY", fromKey: "ibiden", toType: "SEGMENT", toKey: "compute_hardware", edgeType: "MATERIAL", strength: 85, note: "Ibiden ABF 载板供 AI 芯片封装" },
    { fromType: "COMPANY", fromKey: "fujikura", toType: "SEGMENT", toKey: "dc_network", edgeType: "SUPPLY", strength: 90, note: "フジクラ光互连供数据中心网络" },
    { fromType: "COMPANY", fromKey: "takasago_thermal", toType: "SEGMENT", toKey: "cooling", edgeType: "SUPPLY", strength: 88, note: "高砂热学供数据中心散热/液冷工程" },
    { fromType: "COMPANY", fromKey: "fuji_electric", toType: "SEGMENT", toKey: "power_infra", edgeType: "SUPPLY", strength: 85, note: "富士电机供 UPS/配电" },
    { fromType: "COMPANY", fromKey: "hitachi", toType: "SEGMENT", toKey: "power_infra", edgeType: "SUPPLY", strength: 82, note: "日立能源供变压器/输配电" },
    { fromType: "COMPANY", fromKey: "ntt", toType: "SEGMENT", toKey: "dc_facility", edgeType: "SUPPLY", strength: 84, note: "NTT 运营全球数据中心设施" },
    { fromType: "COMPANY", fromKey: "sakura_internet", toType: "SEGMENT", toKey: "hyperscale_cloud", edgeType: "SUPPLY", strength: 78, note: "さくら供本土 GPU 云" },
    // 公司间供应/竞争
    { fromType: "COMPANY", fromKey: "nvidia", toType: "COMPANY", toKey: "supermicro", edgeType: "SUPPLY", strength: 90, note: "NVIDIA GPU 供 Supermicro AI 服务器" },
    { fromType: "COMPANY", fromKey: "nvidia", toType: "COMPANY", toKey: "sakura_internet", edgeType: "SUPPLY", strength: 75, note: "NVIDIA GPU 供さくら GPU 云" },
    { fromType: "COMPANY", fromKey: "ibiden", toType: "COMPANY", toKey: "nvidia", edgeType: "MATERIAL", strength: 80, note: "Ibiden 载板用于 NVIDIA 加速器封装" },
    { fromType: "COMPANY", fromKey: "broadcom", toType: "COMPANY", toKey: "arista", edgeType: "SUPPLY", strength: 85, note: "Broadcom 交换芯片供 Arista 交换机" },
    { fromType: "COMPANY", fromKey: "broadcom", toType: "COMPANY", toKey: "google_cloud", edgeType: "SUPPLY", strength: 80, note: "Broadcom 为谷歌定制 TPU/ASIC" },
    { fromType: "COMPANY", fromKey: "microsoft", toType: "COMPANY", toKey: "nvidia", edgeType: "CUSTOMER", strength: 90, note: "微软采购 NVIDIA GPU 建 AI 云" },
    { fromType: "COMPANY", fromKey: "fujikura", toType: "COMPANY", toKey: "furukawa_electric", edgeType: "COMPETE", directed: false, strength: 80, note: "光缆御三家竞争" },
    { fromType: "COMPANY", fromKey: "furukawa_electric", toType: "COMPANY", toKey: "sumitomo_electric", edgeType: "COMPETE", directed: false, strength: 78, note: "光缆御三家竞争" },
    { fromType: "COMPANY", fromKey: "vertiv", toType: "COMPANY", toKey: "takasago_thermal", edgeType: "COMPETE", directed: false, strength: 60, note: "数据中心散热海外 vs 日本竞合" },
    { fromType: "COMPANY", fromKey: "fuji_electric", toType: "COMPANY", toKey: "schneider", edgeType: "COMPETE", directed: false, strength: 65, note: "UPS/供配电竞争" },
    { fromType: "COMPANY", fromKey: "equinix", toType: "COMPANY", toKey: "ntt", edgeType: "COMPETE", directed: false, strength: 70, note: "托管数据中心海外 vs 日本竞争" },
  ],
};
