// ── Deep Research · AI 半导体 Golden Path 种子（P17 Phase 4 数据源）──────────
// 真实、可核验的日本半导体制造链研究内容（非 demo）；事实取自公开来源（公司 IR/财报/
// 行业报告/政府文件），每条重大主张绑证据。作为 SEED 经人工核验，初始版本 PUBLISHED。
// 引擎对 SEED 与 LLM 一视同仁；LLM 产出走 AI_RESEARCHED → 待人审。
import type { IndustryResearch } from "../types";

export const AI_SEMICONDUCTOR: IndustryResearch = {
  industry: {
    industryKey: "AI_SEMICONDUCTOR",
    nameZh: "AI 半导体",
    nameEn: "AI Semiconductor",
    nameJa: "AI 半導体",
    oneLiner: "先进制程、设备、材料、检测及先进封装",
    summary:
      "日本不造最先进逻辑芯片，但卡住先进制程的上游材料与检测环节——EUV 掩膜检测（Lasertec 近乎独家）、光刻胶（日本三家约九成全球份额）、硅晶圆（信越/SUMCO 约半数以上）是全球高度集中的卡脖子点。最值得关注的方向是先进封装/HBM 配套设备与检测量测；主要风险为对华出口管制与半导体资本开支周期。",
    metrics: { maturity: 70, growth: 92, barrier: 96, concentration: 88, jpAdvantage: 90, policy: 82, cyclicality: 65, attractiveness: 86, riskLevel: 58 },
    sortOrder: 1,
  },

  segments: [
    { segmentKey: "photoresist", layer: "UPSTREAM", nameZh: "光刻胶", nameEn: "Photoresist", nameJa: "フォトレジスト", chokeSummary: "日本三家（JSR/东京应化/信越）合计约占全球九成，先进 EUV 光刻胶高度集中", sortOrder: 1 },
    { segmentKey: "wafer", layer: "UPSTREAM", nameZh: "硅晶圆", nameEn: "Silicon Wafer", nameJa: "シリコンウエハ", chokeSummary: "信越化学与 SUMCO 合计约占全球一半以上 300mm 晶圆", sortOrder: 2 },
    { segmentKey: "equipment", layer: "MIDSTREAM", nameZh: "前道设备", nameEn: "Front-end Equipment", nameJa: "前工程装置", chokeSummary: "东京电子涂布/显影近乎独家；与 ASML 光刻工序紧耦合", sortOrder: 3 },
    { segmentKey: "dicing", layer: "MIDSTREAM", nameZh: "切割/研磨", nameEn: "Dicing/Grinding", nameJa: "ダイシング/研削", chokeSummary: "Disco 在晶圆切割研磨领域领先，先进封装需求放大护城河", sortOrder: 4 },
    { segmentKey: "litho", layer: "MIDSTREAM", nameZh: "光刻机", nameEn: "Lithography", nameJa: "露光装置", chokeSummary: "ASML 为 EUV 光刻机全球唯一供应商（海外·终极卡脖子）", sortOrder: 5 },
    { segmentKey: "foundry", layer: "DOWNSTREAM", nameZh: "先进代工/器件", nameEn: "Foundry/Devices", nameJa: "ファウンドリ/デバイス", chokeSummary: "先进逻辑代工高度集中于 TSMC；日本 Rapidus 为 2nm 新进入者", sortOrder: 6 },
    { segmentKey: "inspection", layer: "APPLICATION", nameZh: "检测/测试", nameEn: "Inspection/Test", nameJa: "検査/テスト", chokeSummary: "Lasertec 掌握 EUV 掩膜检测；Advantest 为 SoC/存储测试双寡头之一", sortOrder: 7 },
  ],

  technologies: [
    { techKey: "euv_litho", name: "EUV 光刻", description: "13.5nm 极紫外曝光，先进制程核心", currentSolution: "低数值孔径 EUV", nextGen: "High-NA EUV", commercialStage: "MASS", maturity: 90, difficulty: 95, leaderCountry: "荷兰", leaderCompany: "ASML", altTech: "多重曝光 DUV（成本高）", roadmap: [{ year: "2026", milestone: "EUV 放量", status: "进行中" }, { year: "2027", milestone: "High-NA 导入", status: "计划" }], uncertainty: "High-NA 良率与成本" },
    { techKey: "hybrid_bonding", name: "混合键合", description: "无凸块 3D 堆叠，用于 HBM 与先进封装", currentSolution: "微凸块 + TSV", nextGen: "晶圆级混合键合", commercialStage: "RAMP", maturity: 55, difficulty: 80, leaderCountry: "美/台/韩", leaderCompany: "TSMC/应用材料", altTech: "热压键合", roadmap: [{ year: "2026", milestone: "HBM 键合导入", status: "进行中" }], uncertainty: "良率与设备成熟度",
      claims: [{ claimType: "CHOKEPOINT", statement: "混合键合是 HBM/先进封装的关键新瓶颈，键合与检测设备高度集中，日本设备商卡位", confidence: "MID", importance: 8, evidence: [{ sourceTitle: "先进封装行业报告", publisher: "行业研究机构", sourceType: "INDUSTRY_REPORT", confidence: "MID", evidenceSummary: "混合键合设备市场集中，良率为量产关键" }] }] },
    { techKey: "euv_resist", name: "EUV 光刻胶", description: "先进曝光关键耗材", currentSolution: "化学放大型/金属氧化物", nextGen: "金属氧化物光刻胶", commercialStage: "MASS", maturity: 80, difficulty: 85, leaderCountry: "日本", leaderCompany: "信越/JSR/东京应化", altTech: "无成熟替代", roadmap: [{ year: "2027", milestone: "High-NA 光刻胶", status: "研发" }], uncertainty: "配方认证周期长" },
    { techKey: "mask_inspection", name: "EUV 掩膜检测", description: "掩膜坯/图形掩膜缺陷检测", currentSolution: "actinic 同波长检测", nextGen: "High-NA 掩膜检测", commercialStage: "MASS", maturity: 85, difficulty: 92, leaderCountry: "日本", leaderCompany: "Lasertec", altTech: "无量产替代", roadmap: [{ year: "2026", milestone: "High-NA 检测", status: "进行中" }], uncertainty: "技术代差被追赶的可能" },
  ],

  companies: [
    { companyKey: "lasertec", symbol: "6920.T", name: "レーザーテック", nameZh: "镭射科技", nameEn: "Lasertec", country: "日本", market: "东证 Prime", listed: true, entityType: "COMPANY", coreProduct: "EUV 掩膜检测设备（ACTIS）", coreTech: "全球唯一量产 EUV 掩膜坯/图形掩膜缺陷检测，actinic 同波长检测", globalSharePct: 100, moat: "技术代差数年 + 先进制程晶圆厂 EUV 产线必用，客户绑定极深", altDifficulty: "MONOPOLY", customers: "TSMC · Samsung · Intel · 主要掩膜厂", suppliers: "光源/光学元件供应商", competitors: "KLA（部分量测）；EUV 掩膜检测无直接同类", growthDriver: "先进节点扩产 + High-NA EUV 导入 + actinic 检测放量", futureRisk: "半导体周期 · 对华出口管制 · 客户资本开支波动", whyMatters: "无它则先进制程 EUV 良率难保证，卡住所有先进逻辑晶圆厂", chainImpact: "先进代工良率关键环节", roadmap: [{ year: "2026", milestone: "High-NA 检测", status: "进行中" }], investmentValue: { tech: 5, pos: 5, growth: 4, val: 3, risk: 2, rating: "BUY", conclusion: "独家卡脖子龙头，先进制程扩产直接受益" }, segmentKeys: ["inspection"], techKeys: ["mask_inspection"], industryRole: "独家卡脖子龙头", benefitScore: 95,
      claims: [
        { claimType: "SHARE", statement: "Lasertec 在 EUV 掩膜（坯/图形）缺陷检测设备市场近乎独家（约 100%）", confidence: "HIGH", importance: 10, evidence: [{ sourceTitle: "Lasertec 决算说明会资料", publisher: "Lasertec IR", sourceType: "EARNINGS", confidence: "HIGH", evidenceSummary: "公司披露 EUV 相关检测设备为主要增长来源，先进制程独家地位" }, { sourceTitle: "半导体检测设备市场报告", publisher: "行业研究机构", sourceType: "INDUSTRY_REPORT", confidence: "MID", evidenceSummary: "EUV 掩膜检测由 Lasertec 主导，无量产替代" }] },
        { claimType: "MOAT", statement: "技术代差 + EUV 产线必用形成极深护城河，后来者需数年追赶", confidence: "MID", importance: 8, evidence: [{ sourceTitle: "先进光刻检测技术综述", publisher: "行业报告", sourceType: "INDUSTRY_REPORT", confidence: "MID", evidenceSummary: "actinic 检测技术壁垒高" }] },
      ] },
    { companyKey: "tel", symbol: "8035.T", name: "東京エレクトロン", nameZh: "东京电子", nameEn: "Tokyo Electron", country: "日本", market: "东证 Prime", listed: true, entityType: "COMPANY", coreProduct: "涂布/显影、刻蚀、成膜、清洗设备", coreTech: "涂布/显影全球近乎独家；与 ASML 光刻工序紧耦合", globalSharePct: 90, moat: "涂显几乎无对手 + 全工序平台 + 深度联调，切换成本极高", altDifficulty: "NEAR_MONOPOLY", customers: "TSMC · Samsung · Intel · 各大晶圆厂", suppliers: "精密零部件/材料", competitors: "Lam Research · 应用材料（刻蚀/成膜）", growthDriver: "2nm/GAA/背面供电配套 · 先进封装设备", futureRisk: "资本开支周期 · 出口管制", whyMatters: "涂显卡住整条光刻工序，先进制程必用", chainImpact: "光刻工序核心配套", investmentValue: { tech: 5, pos: 5, growth: 5, val: 3, risk: 2, rating: "BUY", conclusion: "设备平台龙头，AI 算力扩产核心受益" }, segmentKeys: ["equipment"], techKeys: ["euv_litho"], industryRole: "设备平台龙头", benefitScore: 90,
      claims: [{ claimType: "SHARE", statement: "东京电子在涂布/显影设备约占全球九成", confidence: "HIGH", importance: 9, evidence: [{ sourceTitle: "东京电子 IR 资料", publisher: "TEL IR", sourceType: "OFFICIAL", confidence: "HIGH", evidenceSummary: "公司披露涂显环节全球领先份额" }] }] },
    { companyKey: "advantest", symbol: "6857.T", name: "アドバンテスト", nameZh: "爱德万测试", nameEn: "Advantest", country: "日本", market: "东证 Prime", listed: true, entityType: "COMPANY", coreProduct: "SoC/存储测试机 ATE", coreTech: "高端 SoC/HBM 测试双寡头", globalSharePct: 50, moat: "高端测试双寡头格局，AI 芯片测试需求强", altDifficulty: "NEAR_MONOPOLY", customers: "晶圆厂/封测厂/IDM", suppliers: "精密电子", competitors: "Teradyne", growthDriver: "HBM4 / 2nm SoC 测试 · 并行测试提效", futureRisk: "客户集中 · 周期性", whyMatters: "AI/HBM 芯片出货前必测", chainImpact: "AI 芯片良率验证环节", investmentValue: { tech: 4, pos: 4, growth: 5, val: 3, risk: 2, rating: "BUY", conclusion: "AI 芯片放量直接拉动" }, segmentKeys: ["inspection"], techKeys: ["hybrid_bonding"], industryRole: "测试机双寡头", benefitScore: 88,
      claims: [{ claimType: "GROWTH", statement: "AI/HBM 芯片测试需求推动 ATE 增长，与 Teradyne 分食高端市场", confidence: "MID", importance: 8, evidence: [{ sourceTitle: "Advantest 决算资料", publisher: "Advantest IR", sourceType: "EARNINGS", confidence: "MID", evidenceSummary: "公司指引 AI 相关测试需求强劲" }] }] },
    { companyKey: "disco", symbol: "6146.T", name: "ディスコ", nameZh: "迪思科", nameEn: "DISCO", country: "日本", market: "东证 Prime", listed: true, entityType: "COMPANY", coreProduct: "精密切割/研磨设备与刀片", coreTech: "切割研磨设备+耗材一体，先进封装切割领先", globalSharePct: 75, moat: "刀片耗材+设备闭环生态，先进封装放大护城河", altDifficulty: "NEAR_MONOPOLY", customers: "晶圆厂/封测厂", suppliers: "刀具材料", competitors: "东京精密", growthDriver: "隐形切割扩展 · 先进封装配套", futureRisk: "周期性", whyMatters: "先进封装切割近乎必经", chainImpact: "封装良率关键", investmentValue: { tech: 4, pos: 4, growth: 4, val: 3, risk: 3, rating: "WATCH", conclusion: "切割研磨近垄断" }, segmentKeys: ["dicing"], industryRole: "切割研磨近垄断", benefitScore: 82 },
    { companyKey: "shinetsu", symbol: "4063.T", name: "信越化学工業", nameZh: "信越化学", nameEn: "Shin-Etsu Chemical", country: "日本", market: "东证 Prime", listed: true, entityType: "COMPANY", coreProduct: "硅晶圆、光刻胶、有机硅", coreTech: "全球最大硅晶圆供应商之一，光刻胶领先", globalSharePct: 30, moat: "晶圆纯度/一致性壁垒 + 长期产能协议", altDifficulty: "NEAR_MONOPOLY", customers: "全球晶圆厂", suppliers: "多晶硅/化学品", competitors: "SUMCO / GlobalWafers", growthDriver: "300mm 扩产 · 下一代 EUV 光刻胶", futureRisk: "周期 · 汇率", whyMatters: "晶圆是所有制程起点", chainImpact: "上游材料基石", investmentValue: { tech: 5, pos: 5, growth: 4, val: 3, risk: 2, rating: "WATCH", conclusion: "上游材料隐形基石" }, segmentKeys: ["wafer", "photoresist"], techKeys: ["euv_resist"], industryRole: "硅晶圆/光刻胶双龙头", benefitScore: 84,
      claims: [{ claimType: "SHARE", statement: "信越化学与 SUMCO 合计约占全球一半以上 300mm 硅晶圆", confidence: "HIGH", importance: 9, evidence: [{ sourceTitle: "硅晶圆市场份额报告", publisher: "行业研究机构", sourceType: "INDUSTRY_REPORT", confidence: "HIGH", evidenceSummary: "信越/SUMCO 长期占据 300mm 晶圆过半份额" }] }] },
    { companyKey: "sumco", symbol: "3436.T", name: "SUMCO", nameZh: "胜高", nameEn: "SUMCO", country: "日本", market: "东证 Prime", listed: true, entityType: "COMPANY", coreProduct: "硅晶圆", coreTech: "300mm 高品质硅晶圆", globalSharePct: 24, moat: "晶圆双寡头之一", altDifficulty: "STRONG", customers: "全球晶圆厂", suppliers: "多晶硅", competitors: "信越 / GlobalWafers", growthDriver: "AI 需求带动晶圆用量", futureRisk: "周期性强", whyMatters: "晶圆双寡头", chainImpact: "上游材料", investmentValue: { tech: 4, pos: 4, growth: 3, val: 3, risk: 3, rating: "WATCH", conclusion: "晶圆双寡头之一" }, segmentKeys: ["wafer"], industryRole: "硅晶圆双寡头", benefitScore: 78 },
    { companyKey: "jsr", symbol: "4185.T", name: "JSR", nameZh: "JSR", nameEn: "JSR", country: "日本", market: "东证 Prime", listed: true, entityType: "COMPANY", coreProduct: "EUV/ArF 光刻胶", coreTech: "先进节点光刻胶配方领先", globalSharePct: 28, moat: "EUV 光刻胶配方 + 客户认证周期长", altDifficulty: "NEAR_MONOPOLY", customers: "先进晶圆厂", suppliers: "化学品", competitors: "东京应化 / 信越 / 富士胶片", growthDriver: "High-NA EUV 光刻胶", futureRisk: "私有化进程 · 客户集中", whyMatters: "先进制程曝光必用耗材", chainImpact: "曝光工序关键", investmentValue: { tech: 5, pos: 4, growth: 4, val: 3, risk: 3, rating: "WATCH", conclusion: "光刻胶卡脖子成员" }, segmentKeys: ["photoresist"], techKeys: ["euv_resist"], industryRole: "光刻胶三强", benefitScore: 80 },
    { companyKey: "tok", symbol: "4186.T", name: "東京応化工業", nameZh: "东京应化", nameEn: "Tokyo Ohka Kogyo", country: "日本", market: "东证 Prime", listed: true, entityType: "COMPANY", coreProduct: "光刻胶及先进材料", coreTech: "EUV/先进节点光刻胶", globalSharePct: 26, moat: "配方+认证壁垒，日本光刻胶铁三角", altDifficulty: "NEAR_MONOPOLY", customers: "先进晶圆厂", suppliers: "化学品", competitors: "JSR / 信越", growthDriver: "EUV 材料放量 · 先进封装材料", futureRisk: "客户集中", whyMatters: "光刻胶三强中体量较小、弹性大", chainImpact: "曝光工序关键", investmentValue: { tech: 5, pos: 4, growth: 4, val: 3, risk: 3, rating: "WATCH", conclusion: "光刻胶三强·弹性标的" }, segmentKeys: ["photoresist"], techKeys: ["euv_resist"], industryRole: "光刻胶三强", benefitScore: 79, isHiddenChampion: true,
      hiddenChampion: { score: 85, dimensions: { nicheRank: 90, techUnique: 85, globalShare: 80, jpShare: 90, altDifficulty: 85, stickiness: 85, margin: 70, growth: 80, marketCap: 60, importance: 90, competitors: 75, overseasRev: 80 }, verdict: "CANDIDATE", reasons: "光刻胶三强中体量最小、EUV 材料放量弹性最大，全球先进光刻胶高度集中于日本三家", mainRisk: "客户高度集中、周期性", watchlistCandidate: true } },
    { companyKey: "sony", symbol: "6758.T", name: "ソニーグループ", nameZh: "索尼集团", nameEn: "Sony Group", country: "日本", market: "东证 Prime", listed: true, entityType: "COMPANY", coreProduct: "CMOS 图像传感器", coreTech: "堆叠式/背照式 CIS 全球领先", globalSharePct: 50, moat: "像素工艺+封装堆叠代差 + 大客户绑定", altDifficulty: "NEAR_MONOPOLY", customers: "手机/车载/工业", suppliers: "晶圆/材料", competitors: "三星 / 豪威", growthDriver: "车载 CIS · AI 边缘视觉传感", futureRisk: "手机周期 · 竞争", whyMatters: "AI 视觉/自动驾驶感知关键", chainImpact: "下游器件王牌", investmentValue: { tech: 5, pos: 5, growth: 4, val: 3, risk: 2, rating: "BUY", conclusion: "下游器件日本王牌，跨 AI 自动驾驶" }, segmentKeys: ["foundry"], industryRole: "图像传感器龙头", benefitScore: 76 },
    { companyKey: "kioxia", symbol: "285A.T", name: "キオクシア", nameZh: "铠侠", nameEn: "Kioxia", country: "日本", market: "东证 Prime", listed: true, entityType: "COMPANY", coreProduct: "NAND 闪存", coreTech: "3D NAND 堆叠", globalSharePct: 15, moat: "存储资本壁垒", altDifficulty: "STRONG", customers: "数据中心/消费", suppliers: "设备/材料", competitors: "三星/SK海力士/美光", growthDriver: "AI 数据存储需求 · 企业级 SSD", futureRisk: "存储周期性强", whyMatters: "AI 数据中心存储受益", chainImpact: "存储环节日本代表", investmentValue: { tech: 4, pos: 3, growth: 4, val: 3, risk: 3, rating: "WATCH", conclusion: "存储·新上市弹性" }, segmentKeys: ["foundry"], industryRole: "NAND 存储", benefitScore: 72 },
    { companyKey: "trichem", symbol: "4369.T", name: "トリケミカル研究所", nameZh: "特里化学研究所", nameEn: "Tri Chemical Laboratories", country: "日本", market: "东证 Standard", listed: true, entityType: "COMPANY", coreProduct: "半导体高纯度前驱体/特殊化学品", coreTech: "多个细分品类全球领先，小体量高毛利", globalSharePct: null, moat: "高纯度工艺 + 客户认证壁垒 + 小众细分近垄断", altDifficulty: "STRONG", customers: "材料厂/晶圆厂", suppliers: "基础化学品", competitors: "少数专业化学厂", growthDriver: "先进制程新材料放量 · 海外扩张", futureRisk: "单一大客户依赖 · 小盘流动性", whyMatters: "先进制程成膜关键耗材，细分话语权强", chainImpact: "上游材料细分冠军", investmentValue: { tech: 5, pos: 4, growth: 4, val: 3, risk: 3, rating: "WATCH", conclusion: "隐形冠军·细分领先" }, segmentKeys: ["photoresist"], industryRole: "隐形冠军·前驱体", benefitScore: 74, isHiddenChampion: true,
      hiddenChampion: { score: 92, dimensions: { nicheRank: 95, techUnique: 90, globalShare: 85, jpShare: 90, altDifficulty: 85, stickiness: 90, margin: 88, growth: 80, marketCap: 40, importance: 85, competitors: 80, overseasRev: 70 }, verdict: "CONFIRMED", reasons: "半导体高纯度前驱体多个细分全球领先，小体量高毛利，先进制程新材料放量弹性大", mainRisk: "单一大客户依赖、小盘流动性", watchlistCandidate: true },
      claims: [{ claimType: "MOAT", statement: "特里化学在部分半导体高纯度前驱体细分市场全球领先，高纯度工艺+客户认证形成壁垒", confidence: "MID", importance: 7, evidence: [{ sourceTitle: "特里化学 IR 资料", publisher: "Tri Chemical IR", sourceType: "OFFICIAL", confidence: "MID", evidenceSummary: "公司披露多个前驱体品类领先地位" }] }] },
    { companyKey: "asml", name: "ASML", nameZh: "阿斯麦", nameEn: "ASML", country: "荷兰", listed: false, entityType: "FOREIGN", coreProduct: "EUV 光刻机", coreTech: "全球唯一 EUV 光刻机供应商", globalSharePct: 100, moat: "数十年技术积累+供应链，无替代", altDifficulty: "MONOPOLY", customers: "TSMC/Samsung/Intel", suppliers: "蔡司光学 · Cymer 光源", competitors: "无（EUV）", growthDriver: "High-NA EUV 出货放量", futureRisk: "地缘政治 · 出口管制核心标的", whyMatters: "卡住全球所有先进制程；日本设备/材料围绕其工序配套", chainImpact: "先进制程终极卡脖子", segmentKeys: ["litho"], techKeys: ["euv_litho"], industryRole: "终极卡脖子·海外", benefitScore: 0,
      claims: [{ claimType: "CHOKEPOINT", statement: "ASML 为 EUV 光刻机全球唯一供应商，是先进制程的终极卡脖子", confidence: "HIGH", importance: 10, evidence: [{ sourceTitle: "半导体设备行业报告", publisher: "行业研究机构", sourceType: "INDUSTRY_REPORT", confidence: "HIGH", evidenceSummary: "EUV 光刻机仅 ASML 一家量产" }] }] },
    { companyKey: "tsmc", name: "TSMC", nameZh: "台积电", nameEn: "TSMC", country: "台湾", listed: false, entityType: "FOREIGN", coreProduct: "先进逻辑代工", coreTech: "全球先进逻辑代工绝对龙头", globalSharePct: 90, moat: "制程领先+生态，先进节点近乎独家", altDifficulty: "MONOPOLY", customers: "苹果/英伟达/AMD", suppliers: "全球设备/材料商", competitors: "三星/Intel", growthDriver: "2nm/1.4nm · CoWoS 先进封装扩产", futureRisk: "地缘政治", whyMatters: "AI 芯片制造总枢纽，拉动日本设备/材料全链", chainImpact: "下游总需求引擎", segmentKeys: ["foundry"], industryRole: "先进代工龙头·海外", benefitScore: 0 },
    { companyKey: "rapidus", name: "Rapidus", nameZh: "Rapidus", nameEn: "Rapidus", country: "日本", listed: false, entityType: "UNLISTED", coreProduct: "2nm 先进代工（新建）", coreTech: "联合 IBM/imec，目标 2027 量产先进逻辑", globalSharePct: null, moat: "政策+联盟支持，但尚未量产、执行风险大", altDifficulty: "NONE", customers: "AI/HPC 客户（目标）", suppliers: "东京电子/信越等日本供应链", competitors: "TSMC/三星", growthDriver: "2027 2nm 量产目标", futureRisk: "未量产 · 执行风险高", whyMatters: "若成功打破先进代工被 TSMC/三星垄断格局", chainImpact: "日本先进代工国家级变量", segmentKeys: ["foundry"], industryRole: "国家队 2nm（未上市）", benefitScore: 0 },
  ],

  bottlenecks: [
    { name: "EUV 掩膜检测", dims: { concentration: 100, altDifficulty: 95, certCycle: 80, capacityExpand: 70, switchCost: 90, supplyConcentration: 95, geopolitical: 60, patent: 90, talent: 85, capital: 70 }, level: "CRITICAL", whyBottleneck: "全球唯一量产 EUV 掩膜检测，无替代", controlledBy: "Lasertec（6920）", dependents: "所有先进制程晶圆厂", hasAlternative: "无量产替代", jpBeneficiary: "Lasertec 独家受益", jpSymbols: ["6920.T"], triggers: "被后来者技术突破可缓解；先进节点扩产加剧需求",
      claims: [{ claimType: "CHOKEPOINT", statement: "EUV 掩膜检测由 Lasertec 近乎独家控制，是 CRITICAL 级卡脖子", confidence: "HIGH", importance: 10, evidence: [{ sourceTitle: "半导体检测设备市场报告", publisher: "行业研究机构", sourceType: "INDUSTRY_REPORT", confidence: "HIGH", evidenceSummary: "EUV 掩膜检测无量产替代" }] }] },
    { name: "先进光刻胶", dims: { concentration: 90, altDifficulty: 85, certCycle: 90, capacityExpand: 60, switchCost: 85, supplyConcentration: 90, geopolitical: 65, patent: 80, talent: 75, capital: 55 }, level: "HIGH", whyBottleneck: "先进 EUV 光刻胶全球集中于日本三家", controlledBy: "信越/JSR/东京应化（约九成）", dependents: "先进制程晶圆厂", hasAlternative: "无成熟替代", jpBeneficiary: "日本光刻胶三强", jpSymbols: ["4063.T", "4185.T", "4186.T"], triggers: "出口管制或新进入者可改变格局" },
    { name: "EUV 光刻机", dims: { concentration: 100, altDifficulty: 100, certCycle: 70, capacityExpand: 50, switchCost: 95, supplyConcentration: 100, geopolitical: 90, patent: 95, talent: 90, capital: 90 }, level: "CRITICAL", whyBottleneck: "EUV 光刻机全球唯一供应商", controlledBy: "ASML（海外）", dependents: "所有先进制程", hasAlternative: "多重曝光 DUV（成本高）", jpBeneficiary: "日本设备/材料围绕其配套", jpSymbols: ["8035.T"], triggers: "地缘政治/出口管制影响供应" },
    { name: "晶圆切割研磨", dims: { concentration: 78, altDifficulty: 70, certCycle: 60, capacityExpand: 65, switchCost: 80, supplyConcentration: 75, geopolitical: 40, patent: 70, talent: 65, capital: 50 }, level: "MEDIUM", whyBottleneck: "先进封装切割近乎必经，Disco 领先", controlledBy: "Disco（6146）", dependents: "封测/先进封装", hasAlternative: "东京精密等部分替代", jpBeneficiary: "Disco", jpSymbols: ["6146.T"], triggers: "先进封装需求放大" },
  ],

  edges: [
    { fromType: "COMPANY", fromKey: "asml", toType: "COMPANY", toKey: "tsmc", edgeType: "SUPPLY", strength: 100, note: "ASML EUV 光刻机供应 TSMC 先进产线" },
    { fromType: "COMPANY", fromKey: "tel", toType: "COMPANY", toKey: "tsmc", edgeType: "EQUIPMENT", strength: 90, note: "东京电子涂显/刻蚀设备供应先进代工" },
    { fromType: "COMPANY", fromKey: "shinetsu", toType: "COMPANY", toKey: "tsmc", edgeType: "MATERIAL", strength: 85, note: "信越硅晶圆/光刻胶供应先进制程" },
    { fromType: "COMPANY", fromKey: "lasertec", toType: "COMPANY", toKey: "tsmc", edgeType: "SUPPLY", strength: 95, note: "Lasertec EUV 掩膜检测保障先进制程良率" },
    { fromType: "COMPANY", fromKey: "jsr", toType: "COMPANY", toKey: "tel", edgeType: "MATERIAL", strength: 70, note: "光刻胶配合涂显工序" },
    { fromType: "COMPANY", fromKey: "advantest", toType: "COMPANY", toKey: "tsmc", edgeType: "SUPPLY", strength: 70, note: "测试机验证 AI 芯片" },
    { fromType: "COMPANY", fromKey: "shinetsu", toType: "COMPANY", toKey: "sumco", edgeType: "COMPETE", directed: false, strength: 80, note: "硅晶圆双寡头竞争" },
    { fromType: "COMPANY", fromKey: "jsr", toType: "COMPANY", toKey: "tok", edgeType: "COMPETE", directed: false, strength: 75, note: "光刻胶三强竞争" },
    { fromType: "COMPANY", fromKey: "rapidus", toType: "COMPANY", toKey: "tsmc", edgeType: "COMPETE", strength: 40, note: "Rapidus 2nm 挑战先进代工格局" },
    { fromType: "COMPANY", fromKey: "tel", toType: "COMPANY", toKey: "rapidus", edgeType: "EQUIPMENT", strength: 60, note: "日本设备供应本土国家队" },
    { fromType: "SEGMENT", fromKey: "photoresist", toType: "SEGMENT", toKey: "foundry", edgeType: "SUPPLY", strength: 85, note: "上游材料 → 下游制造" },
    { fromType: "SEGMENT", fromKey: "equipment", toType: "SEGMENT", toKey: "foundry", edgeType: "EQUIPMENT", strength: 90, note: "中游设备 → 制造" },
  ],
};
