#!/usr/bin/env npx tsx
/**
 * scripts/day-strategy.ts  — Day Trade Strategy Engine  (v1.0.0)
 *
 * Day Trade 设计 (Trading-Architecture.md §3):
 *   - 资金池    ¥30,000,000  (DAY_TRADE)
 *   - 最大持仓  5只  等权分配  每只 ¥6,000,000
 *   - 止盈线    +1.5%
 *   - 止损线    -1.0%
 *   - 强制平仓  当日收盘（本脚本用 DailyPrice.close 模拟）
 *   - 禁止隔夜
 *
 * 执行流程:
 *   1. 确定 tradeDate（从 StrategyRecommendation 取最新日期）
 *   2. 检查是否交易日（周末/节假日跳过）
 *   3. 读取 StrategyRecommendation（由 generate-strategy-recs 预先生成）
 *   4. 幂等检查（当日 TradeResult 已存在则跳过）
 *   5. 读取开盘/收盘价
 *   6. 计算交易结果 + TOPIX Alpha
 *   7. 写入 StrategyTradeResult / StrategySnapshot / StrategyCapitalLog
 *
 * Usage:
 *   npm run day-strategy           # 处理最新可用交易日
 *   npm run day-strategy:dry       # Dry Run（不写 DB）
 *   npx tsx scripts/day-strategy.ts --date=2026-06-26
 *   npx tsx scripts/day-strategy.ts --dry-run --date=2026-06-26
 */

import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

// ── Constants (per Trading-Architecture.md §3 & §7) ──────────────────────────
const STRATEGY_TYPE    = "DAY_TRADE";
const POOL_INITIAL     = 30_000_000;     // ¥30M
const MAX_POSITIONS    = 5;
const POSITION_SIZE    = POOL_INITIAL / MAX_POSITIONS; // ¥6M per stock
const TAKE_PROFIT_PCT  = 1.5;            // +1.5%
const STOP_LOSS_PCT    = -1.0;           // -1.0%

// ── CLI args ──────────────────────────────────────────────────────────────────
const DRY_RUN   = process.argv.includes("--dry-run");
const dateArg   = process.argv.find(a => a.startsWith("--date="))?.split("=")[1];

// ── Prisma ────────────────────────────────────────────────────────────────────
const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma  = new PrismaClient({ adapter });

// ── Helpers ───────────────────────────────────────────────────────────────────
function jstDate(d?: Date): Date {
  const src  = d ?? new Date();
  const jst  = new Date(src.getTime() + 9 * 3600_000);
  return new Date(Date.UTC(jst.getUTCFullYear(), jst.getUTCMonth(), jst.getUTCDate()));
}

function isWeekend(date: Date): boolean {
  const dow = date.getUTCDay();
  return dow === 0 || dow === 6;
}

function fmt(n: number, dec = 2): string {
  return n.toFixed(dec);
}

function fmtYen(n: number): string {
  return `¥${Math.round(n).toLocaleString("ja-JP")}`;
}

function exitReason(returnPct: number): string {
  if (returnPct >= TAKE_PROFIT_PCT) return "TAKE_PROFIT";
  if (returnPct <= STOP_LOSS_PCT)   return "STOP_LOSS";
  return "DAY_CLOSE";
}

// ── Log ───────────────────────────────────────────────────────────────────────
const startedAt = new Date();
let   stepIdx   = 0;
function step(msg: string) {
  stepIdx++;
  const elapsed = ((Date.now() - startedAt.getTime()) / 1000).toFixed(1);
  console.log(`\n[Step ${stepIdx}] ${msg}  (+${elapsed}s)`);
}

function row(label: string, value: string | number) {
  console.log(`  ${label.padEnd(28)} ${value}`);
}

// ═══════════════════════════════════════════════════════════════════════════════
async function main() {
  console.log("═".repeat(62));
  console.log(`  Day Trade Strategy Engine${DRY_RUN ? "  🔍 DRY RUN" : ""}`);
  console.log(`  Started: ${startedAt.toLocaleString("ja-JP", { timeZone: "Asia/Tokyo" })} JST`);
  console.log("═".repeat(62));

  // ── Step 1: Determine tradeDate ─────────────────────────────────────────────
  step("Determine tradeDate");

  let tradeDate: Date;

  if (dateArg) {
    // Explicit date from CLI
    const [y, m, d] = dateArg.split("-").map(Number);
    tradeDate = new Date(Date.UTC(y, m - 1, d));
    row("Mode", "explicit --date");
    row("tradeDate", dateArg);
  } else {
    // Auto: use latest StrategyRecommendation date (generated by generate-strategy-recs)
    const latestSR = await (prisma as any).strategyRecommendation.findFirst({
      where: { strategyType: STRATEGY_TYPE },
      orderBy: { tradeDate: "desc" },
      select: { tradeDate: true },
    });

    if (!latestSR) {
      console.log("\n⚠  No StrategyRecommendation (DAY_TRADE) found.");
      console.log("   Run: npm run generate-strategy-recs");
      await prisma.$disconnect();
      return;
    }

    tradeDate = jstDate(latestSR.tradeDate as Date);
    row("Mode", "auto (latest StrategyRecommendation)");
    row("tradeDate", tradeDate.toISOString().slice(0, 10));
  }

  const tradeDateStr = tradeDate.toISOString().slice(0, 10);

  // ── Step 2: Trading day check ───────────────────────────────────────────────
  step("Check TSE trading day");

  if (isWeekend(tradeDate)) {
    const dow = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"][tradeDate.getUTCDay()];
    console.log(`\n🚫 ${tradeDateStr} is a weekend (${dow}) — market closed.`);
    console.log("   No trades generated.  exitReason: MARKET_CLOSED");
    await prisma.$disconnect();
    return;
  }
  row("Day of week", ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"][tradeDate.getUTCDay()]);

  // Check if prices exist at all for this date (holiday detection)
  const priceCount = await (prisma as any).dailyPrice.count({ where: { date: tradeDate } });
  if (priceCount === 0) {
    console.log(`\n🚫 No DailyPrice data for ${tradeDateStr} — holiday or data not yet synced.`);
    console.log("   No trades generated.  exitReason: MARKET_CLOSED");
    await prisma.$disconnect();
    return;
  }
  row("DailyPrice rows for date", priceCount);

  // ── Step 3: Load StrategyRecommendation (from generate-strategy-recs) ────────
  step("Load StrategyRecommendation");

  const srRecs = await (prisma as any).strategyRecommendation.findMany({
    where: { strategyType: STRATEGY_TYPE, tradeDate },
    orderBy: { rank: "asc" },
    take: MAX_POSITIONS,
    select: { symbol: true, rank: true, aiScore: true },
  });

  if (srRecs.length === 0) {
    console.log(`\n⚠  No StrategyRecommendation for ${tradeDateStr} (${STRATEGY_TYPE}).`);
    console.log("   Run: npm run generate-strategy-recs -- before running strategies.");
    await prisma.$disconnect();
    return;
  }

  const candidates = (srRecs as any[]).map(r => ({
    symbol:  r.symbol  as string,
    rank:    r.rank    as number,
    aiScore: r.aiScore as number | null,
  }));

  row("StrategyRecommendation", srRecs.length);
  console.log("\n  Candidates:");
  candidates.forEach(c => console.log(`    #${c.rank}  ${c.symbol}  score=${fmt(c.aiScore ?? 0, 1)}`));

  // ── Step 5: Idempotency check ───────────────────────────────────────────────
  step("Idempotency check");

  const existingTrades = await (prisma as any).strategyTradeResult.count({
    where: { strategyType: STRATEGY_TYPE, tradeDate },
  });

  if (existingTrades > 0) {
    console.log(`\n✅ StrategyTradeResult already exists for ${tradeDateStr} (${existingTrades} records). Skipping.`);
    await printSummaryFromDB(tradeDate);
    await prisma.$disconnect();
    return;
  }
  row("Existing trades", 0);

  // ── Step 6: Load prices ─────────────────────────────────────────────────────
  step("Load DailyPrice (open, close)");

  const symbols = candidates.map(c => c.symbol);

  const prices = await (prisma as any).dailyPrice.findMany({
    where: { symbol: { in: symbols }, date: tradeDate },
    select: { symbol: true, open: true, close: true, high: true, low: true },
  });

  const priceMap = new Map<string, { open: number; close: number; high: number; low: number }>(
    (prices as any[]).map((p: any) => [p.symbol, {
      open: p.open, close: p.close, high: p.high, low: p.low,
    }])
  );

  const missingPrices = symbols.filter(s => !priceMap.has(s));
  if (missingPrices.length > 0) {
    console.log(`  ⚠  Missing prices for: ${missingPrices.join(", ")}`);
  }

  // ── Step 7: Load TOPIX return ───────────────────────────────────────────────
  step("Load TOPIX return (for Alpha)");

  const gm = await (prisma as any).globalMarket.findUnique({
    where: { date: tradeDate },
    select: { topixChange: true },
  });

  const topixReturn = (gm as any)?.topixChange ?? null;
  row("TOPIX 1d return", topixReturn != null ? `${fmt(topixReturn)}%` : "N/A");

  // ── Step 8: Load current capital state ─────────────────────────────────────
  step("Load capital pool state");

  const latestCapLog = await (prisma as any).strategyCapitalLog.findFirst({
    where: { strategyType: STRATEGY_TYPE },
    orderBy: { createdAt: "desc" },
  });

  const poolTotal = (latestCapLog as any)?.totalAfter ?? POOL_INITIAL;
  row("Pool total (before trade)", fmtYen(poolTotal));

  // ── Step 9: Calculate trades ────────────────────────────────────────────────
  step("Calculate trade results");

  type TradeCalc = {
    symbol:        string;
    rank:          number;
    entryPrice:    number;
    exitPrice:     number;
    quantity:      number;
    investedAmount: number;
    exitValue:     number;
    returnPct:     number;
    returnAmount:  number;
    topixReturnPct: number | null;
    alpha:         number | null;
    win:           boolean;
    exitReason:    string;
    status:        string;
    waitingOpen:   boolean;
    waitingClose:  boolean;
  };

  const trades: TradeCalc[] = [];

  for (const c of candidates) {
    const p = priceMap.get(c.symbol);

    if (!p || !p.open || p.open <= 0) {
      // No open price
      trades.push({
        symbol: c.symbol, rank: c.rank,
        entryPrice: 0, exitPrice: 0, quantity: 0,
        investedAmount: 0, exitValue: 0,
        returnPct: 0, returnAmount: 0,
        topixReturnPct: topixReturn, alpha: null,
        win: false, exitReason: "DATA_MISSING",
        status: "WAITING_OPEN", waitingOpen: true, waitingClose: false,
      });
      continue;
    }

    const qty = Math.floor(POSITION_SIZE / p.open / 100) * 100;
    if (qty <= 0) {
      // Share price too high for one lot (100 shares) within POSITION_SIZE —
      // this is a permanent condition for this trade date, not missing data.
      // Must not be tagged WAITING_OPEN: entryPrice is already known and no
      // future price sync will ever resolve it.
      trades.push({
        symbol: c.symbol, rank: c.rank,
        entryPrice: p.open, exitPrice: 0, quantity: 0,
        investedAmount: 0, exitValue: 0,
        returnPct: 0, returnAmount: 0,
        topixReturnPct: topixReturn, alpha: null,
        win: false, exitReason: "LOT_SIZE_TOO_SMALL",
        status: "SKIPPED_LOT_SIZE", waitingOpen: false, waitingClose: false,
      });
      continue;
    }

    if (!p.close || p.close <= 0) {
      // No close price
      trades.push({
        symbol: c.symbol, rank: c.rank,
        entryPrice: p.open, exitPrice: 0, quantity: qty,
        investedAmount: qty * p.open, exitValue: 0,
        returnPct: 0, returnAmount: 0,
        topixReturnPct: topixReturn, alpha: null,
        win: false, exitReason: "DATA_MISSING",
        status: "WAITING_CLOSE", waitingOpen: false, waitingClose: true,
      });
      continue;
    }

    const invested   = qty * p.open;
    const exitVal    = qty * p.close;
    const retPct     = ((p.close - p.open) / p.open) * 100;
    const retAmt     = exitVal - invested;
    const reason     = exitReason(retPct);
    const alpha      = topixReturn != null ? retPct - topixReturn : null;

    trades.push({
      symbol:        c.symbol,
      rank:          c.rank,
      entryPrice:    p.open,
      exitPrice:     p.close,
      quantity:      qty,
      investedAmount: invested,
      exitValue:     exitVal,
      returnPct:     retPct,
      returnAmount:  retAmt,
      topixReturnPct: topixReturn,
      alpha,
      win:           retPct > 0,
      exitReason:    reason,
      status:        "CLOSED",
      waitingOpen:   false,
      waitingClose:  false,
    });
  }

  // Summary stats
  const closedTrades   = trades.filter(t => t.status === "CLOSED");
  const winTrades      = closedTrades.filter(t => t.win);
  const winRate        = closedTrades.length > 0 ? winTrades.length / closedTrades.length : 0;
  const totalReturn    = closedTrades.reduce((s, t) => s + t.returnAmount, 0);
  const totalInvested  = closedTrades.reduce((s, t) => s + t.investedAmount, 0);
  const avgReturnPct   = closedTrades.length > 0
    ? closedTrades.reduce((s, t) => s + t.returnPct, 0) / closedTrades.length : 0;
  const validAlphas    = closedTrades.filter(t => t.alpha != null);
  const avgAlpha       = validAlphas.length > 0
    ? validAlphas.reduce((s, t) => s + (t.alpha ?? 0), 0) / validAlphas.length : null;

  const newPoolTotal   = poolTotal + totalReturn;
  const cumulativeRet  = ((newPoolTotal - POOL_INITIAL) / POOL_INITIAL) * 100;

  console.log("\n  Trade results:");
  console.log(`  ${"Symbol".padEnd(10)} ${"Entry".padStart(8)} ${"Exit".padStart(8)} ${"Qty".padStart(6)} ${"Ret%".padStart(7)} ${"Reason"}`);
  console.log(`  ${"-".repeat(60)}`);
  for (const t of trades) {
    const retStr = t.status === "CLOSED" ? `${t.returnPct >= 0 ? "+" : ""}${fmt(t.returnPct)}%` : t.status;
    console.log(
      `  ${t.symbol.padEnd(10)} ${String(t.entryPrice.toFixed(0)).padStart(8)} ${String(t.exitPrice.toFixed(0)).padStart(8)}` +
      ` ${String(t.quantity).padStart(6)} ${retStr.padStart(7)} ${t.exitReason}`
    );
  }

  console.log(`\n  Closed trades:  ${closedTrades.length} / ${trades.length}`);
  console.log(`  Win rate:       ${fmt(winRate * 100, 1)}%  (${winTrades.length}W / ${closedTrades.length - winTrades.length}L)`);
  console.log(`  Avg return:     ${avgReturnPct >= 0 ? "+" : ""}${fmt(avgReturnPct)}%`);
  console.log(`  Total P&L:      ${fmtYen(totalReturn)}`);
  console.log(`  Pool before:    ${fmtYen(poolTotal)}`);
  console.log(`  Pool after:     ${fmtYen(newPoolTotal)}`);
  if (avgAlpha != null) {
    console.log(`  Avg Alpha:      ${avgAlpha >= 0 ? "+" : ""}${fmt(avgAlpha)}% vs TOPIX`);
  }

  // ── Step 10: Write to DB ────────────────────────────────────────────────────
  step(DRY_RUN ? "DB write skipped (Dry Run)" : "Write to database");

  if (DRY_RUN) {
    console.log("\n  [DRY RUN] Would write:");
    console.log(`    StrategyTradeResult  × ${trades.length}`);
    console.log(`    StrategySnapshot     × 1  (${tradeDateStr}  DAY_TRADE)`);
    console.log(`    StrategyCapitalLog   × 1`);
    console.log("\n✅ Dry Run complete — no changes made.");
    await prisma.$disconnect();
    return;
  }

  // Write StrategyTradeResult
  for (const t of trades) {
    await (prisma as any).strategyTradeResult.upsert({
      where: {
        strategyType_tradeDate_symbol: {
          strategyType: STRATEGY_TYPE,
          tradeDate,
          symbol: t.symbol,
        },
      },
      create: {
        strategyType:    STRATEGY_TYPE,
        tradeDate,
        symbol:          t.symbol,
        entryDate:       tradeDate,
        entryPrice:      t.entryPrice > 0 ? t.entryPrice : null,
        exitDate:        t.status === "CLOSED" ? tradeDate : null,
        exitPrice:       t.exitPrice > 0 ? t.exitPrice : null,
        quantity:        t.quantity,
        investedAmount:  t.investedAmount > 0 ? t.investedAmount : null,
        exitValue:       t.exitValue > 0 ? t.exitValue : null,
        returnPct:       t.status === "CLOSED" ? t.returnPct : null,
        returnAmount:    t.status === "CLOSED" ? t.returnAmount : null,
        topixReturnPct:  t.topixReturnPct,
        alpha:           t.alpha,
        win:             t.status === "CLOSED" ? t.win : null,
        holdingDays:     t.status === "CLOSED" ? 1 : null,
        exitReason:      t.exitReason,
        status:          t.status,
      },
      update: {},
    });
  }
  console.log(`  ✅ StrategyTradeResult × ${trades.length} written`);

  // Write StrategySnapshot (CREATE-only — skip if already exists)
  const existingSnap = await (prisma as any).strategySnapshot.findUnique({
    where: {
      strategyType_snapshotDate: {
        strategyType: STRATEGY_TYPE,
        snapshotDate: tradeDate,
      },
    },
  });

  if (existingSnap) {
    console.log("  ℹ  StrategySnapshot already exists — skipped (CREATE-only)");
  } else {
    await (prisma as any).strategySnapshot.create({
      data: {
        strategyType:        STRATEGY_TYPE,
        snapshotDate:        tradeDate,
        totalValue:          newPoolTotal,
        cash:                newPoolTotal,       // Day Trade: full cash at end of day
        investedValue:       0,                  // no overnight positions
        dailyReturnPct:      totalInvested > 0
          ? (totalReturn / totalInvested) * 100
          : 0,
        cumulativeReturnPct: cumulativeRet,
        topixReturnPct:      topixReturn,
        alpha:               avgAlpha,
        winRate:             winRate,
        openPositions:       0,                  // Day Trade: always 0 at end of day
        closedTrades:        closedTrades.length,
      },
    });
    console.log("  ✅ StrategySnapshot created");
  }

  // Write StrategyCapitalLog
  await (prisma as any).strategyCapitalLog.create({
    data: {
      strategyType:    STRATEGY_TYPE,
      logDate:         tradeDate,
      cashBefore:      poolTotal,
      cashAfter:       newPoolTotal,
      investedBefore:  0,          // no overnight coming in
      investedAfter:   0,          // no overnight going out
      totalBefore:     poolTotal,
      totalAfter:      newPoolTotal,
      changeAmount:    totalReturn,
      changeReason:    `DAY_CLOSE ${tradeDateStr} ${closedTrades.length}trades W${winTrades.length}L${closedTrades.length - winTrades.length}`,
    },
  });
  console.log("  ✅ StrategyCapitalLog updated");

  // ── Final summary ───────────────────────────────────────────────────────────
  const elapsed = ((Date.now() - startedAt.getTime()) / 1000).toFixed(1);
  console.log("\n" + "═".repeat(62));
  console.log(`  Day Strategy Complete — ${tradeDateStr}`);
  console.log(`  Trades:  ${closedTrades.length} closed | ${trades.filter(t => t.waitingOpen).length} WAITING_OPEN | ${trades.filter(t => t.waitingClose).length} WAITING_CLOSE`);
  console.log(`  Win:     ${winTrades.length}/${closedTrades.length}  (${fmt(winRate, 1)}%)`);
  console.log(`  P&L:     ${fmtYen(totalReturn)}`);
  console.log(`  Pool:    ${fmtYen(poolTotal)} → ${fmtYen(newPoolTotal)}`);
  console.log(`  Cumul:   ${cumulativeRet >= 0 ? "+" : ""}${fmt(cumulativeRet)}% since inception`);
  if (avgAlpha != null) console.log(`  Alpha:   ${avgAlpha >= 0 ? "+" : ""}${fmt(avgAlpha)}% vs TOPIX`);
  console.log(`  Elapsed: ${elapsed}s`);
  console.log("═".repeat(62));

  await prisma.$disconnect();
}

// ── Print summary from existing DB records (already-processed days) ─────────
async function printSummaryFromDB(tradeDate: Date) {
  const tradeDateStr = tradeDate.toISOString().slice(0, 10);
  const trades = await (prisma as any).strategyTradeResult.findMany({
    where: { strategyType: STRATEGY_TYPE, tradeDate },
    select: { symbol: true, returnPct: true, returnAmount: true, win: true, status: true, exitReason: true },
  });
  const closed = (trades as any[]).filter(t => t.status === "CLOSED");
  const wins   = closed.filter(t => t.win);
  const pnl    = closed.reduce((s: number, t: any) => s + (t.returnAmount ?? 0), 0);

  console.log(`\n  Already processed: ${tradeDateStr}`);
  console.log(`  Closed: ${closed.length}/${(trades as any[]).length}  Wins: ${wins.length}  P&L: ${fmtYen(pnl)}`);
  (trades as any[]).forEach((t: any) => {
    const ret = t.returnPct != null ? `${t.returnPct >= 0 ? "+" : ""}${fmt(t.returnPct)}%` : t.status;
    console.log(`    ${t.symbol.padEnd(10)} ${ret.padStart(8)}  ${t.exitReason}`);
  });
}

// ── Entry ─────────────────────────────────────────────────────────────────────
main().catch(e => {
  console.error("\n❌ Day Strategy Engine crashed:", e);
  prisma.$disconnect().finally(() => process.exit(1));
});
